var g_choices_x = [
		  
		  [".AUTOM 2 11/15/2021 Corp","PPCR: US TREASURY AUTO"],
		  [".B 0 02/01/2004 Corp","PPCR: TREASURY BILL"],
		  [".B 0 02/01/2025 Corp","PPCR: TREASURY BILL"],
	      [".AUTOM 2 11/15/2011 Corp","PPCR: US TREASURY AUTO"],
          [".B 0 01/01/2004 Corp","PPCR: TREASURY BILL"],
          [".B 0 01/01/2015 Corp","PPCR: TREASURY BILL"], 
          [".I 0 01/01/2016 Corp","PPCR: TREASURY BILL	X"],
          ["IBM US Equity","Internation Business Machines Corp (U.S.)"],
          ["IBM US 4.7 2/19/2046 Corp","Internation Business Machines Corp "],
          ["INDU Index","Dow Jones Industrial Average"],
          ["I US Equity","Intelsat SA(U.S.)"],
          ["ISPIM Corp","Intesa Sanpaolo SpA"],
          ["I17330Y Index" , "KRW Korea Treasury Bond (IYC 173) Zero Coupon Yield 30 Year"],
          ["1128 HK Equity","Wynn Macau Ltd (Hong Kong)"],
		  ["1122 HK Equity","Qingling Motors Co Ltd (Hong Kong)"],
		  ["1125 HK Equity","Lai Fung Holdings Ltd (Hong Kong)"],
		  ["1124z MK Equity","Feration of Malaysia (Bursa Malaysia)"], 
          ];

 var g_choices_backup=[];
 var g_choices
 = [
 ["IBM US Equity","Internation Business Machines Corp (U.S.)"],
          ["IBM US 4.7 2/19/2046 Corp","Internation Business Machines Corp "],
          ["INDU Index","Dow Jones Industrial Average"],
          ["I US Equity","Intelsat SA(U.S.)"],
          ["ISPIM Corp","Intesa Sanpaolo SpA"],
          ["I17330Y Index" , "KRW Korea Treasury Bond (IYC 173) Zero Coupon Yield 30 Year"],

["TYCO US Equity" , "Tayco Developments Inc (U.S.)"],
["TYC US Equity" , "Tyco International Plc (U.S.)"],
["TEL US Equity" , "TE Connectivity Ltd (U.S.)"],
["TEL Corp" , "Tyco Electronics Group SA (Multiple Matches)"],
["TYCOLEV Index" , "Turkey Capacity Utilization NSA"],
["TYC Corp" , "Tyco International Finance SA (Multiple Matches)"],
["TYCOIF CP Mmkt" , "Tyco International Finance SA"],
["TYC GB USD SR 10Y Corp" , "Tyco International Finance SA Generic Benchmark 10Y Corporate"],
["TEL GB USD SR 10Y Corp" , "Tyco Electronics Group SA Generic Benchmark 10Y Corporate"],
["TYCOEL CP Mmkt" , "Tyco Electronics Group SA"],
["TYC GB USD SR 30Y Corp" , "Tyco International Finance SA Generic Benchmark 30Y Corporate"],
["TYC UN Equity" , "Tyco International Plc (New York)"],
["TEL GB USD SR 3Y Corp" , "Tyco Electronics Group SA Generic Benchmark 3Y Corporate"],
["BL193797 Corp" , "Tyco International Holding Loan USD TL 09/10/2019"],
["TYCOLEVS Index" , "Turkey Capacity Utilization SA"],
["TYCO ELE CDS USD SR 5Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO IT Equity" , "Taya Communication Ltd (Tel Aviv)"],
["TYC CDS USD SR 5Y D14 Corp" , "Tyco International Plc"],
["TYCOAL Corp" , "Taiyuan Coal Gasification Co Ltd (Multiple Matches)"],
["TYCORNZ NZ Equity" , "Nikko AM Core Equity Fund (NZX)"],
["0141918D LX Equity" , "Tyco Electronics Group SA"],
["BL193794 Corp" , "Tyco International Loan USD BRIDGE 03/07/2017"],
["TYC BH Equity" , "Tyco International Plc (Bermuda Stock Exchange)"],
["TYCO18 Index" , "Turkey Capacity Utilization Rate Printing & Reproduction Recorded Media"],
["TYCO20 Index" , "Turkey Capacity Utilization Rate Manufacture Chemicals & Chemical Products"],
["TYCO24 Index" , "Turkey Capacity Utilization Rate Manufacture Basic Metals"],
["TYCO28 Index" , "Turkey Capacity Utilization Rate Manufacture Machinery & Equipment nec"],
["4119398Z LX Equity" , "Tyco International Finance SA"],
["TYI LN Equity" , "Tyco International Plc (London)"],
["BL065034 Corp" , "Tyco International Loan USD REV 08/07/2020"],
["PNR Corp" , "Pentair Finance SA (Multiple Matches)"],
["TYCN TB Equity" , "Tycoons Worldwide Group Thailand PCL (Bangkok)"],
["BL814923 Corp" , "TE Connectivity Loan USD REV 12/09/2020"],
["TYC CDS USD SR 4Y D14 Corp" , "Tyco International Plc"],
["TYCO11 Index" , "Turkey Capacity Utilization Rate Manufacture Beverages"],
["TYCO16 Index" , "Turkey Capacity Utilization Rate Manufacture Wood and Products of Wood & Cork"],
["TYCOEZ JP Equity" , "Tyco Electronics Japan GK"],
["TYCOON Corp" , "Tycoons Group Enterprise (Multiple Matches)"],
["611647Q US Equity" , "Tyco Electronics Corp (U.S.)"],
["TYIG IX Equity" , "Tyco International Plc (Chi-X Europe)"],
["BL197340 Corp" , "Tyco International Loan USD REV 08/07/2020"],
["0252711D FP Equity" , "Tyco Flow Control Europe SAS"],
["TYCO10 Index" , "Turkey Capacity Utilization Rate Manufacture Food Products"],
["TYCO12 Index" , "Turkey Capacity Utilization Rate Manufacture Tobacco Products"],
["TYCO30 Index" , "Turkey Capacity Utilization Rate Manufacture Other Transport Equipment"],
["TYCOC11 Index" , "Turkey Capacity Utilization Rate Food & Beverages"],
["TYCOCG Index" , "Turkey Capacity Utilization Rate Consumer Goods"],
["TYCODG Index" , "Turkey Capacity Utilization Rate Durable Consumer Goods"],
["TYCOEL CPIB Mmkt" , "Tyco Electronics Group SA"],
["TYCOEZ CH Equity" , "Tyco Electronics AMP Guangdong Ltd"],
["TYCOFZ CH Equity" , "Pentair Flow Control Beijing Co Ltd"],
["TYCOHZ CH Equity" , "Tyco Healthcare International Trading Shanghai Co Ltd"],
["TYCOIG Index" , "Turkey Capacity Utilization Rate Intermediate Goods"],
["TYCOKG Index" , "Turkey Capacity Utilization Rate Investment Goods"],
["TYCOND Index" , "Turkey Capacity Utilization Rate Nondurable Consumer Goods"],
["TYCO13 Index" , "Turkey Capacity Utilization Rate Manufacture Textiles"],
["TYCO14 Index" , "Turkey Capacity Utilization Rate Manufacture Wearing Apparel"],
["TYCO15 Index" , "Turkey Capacity Utilization Rate Manufacture Leather & Related Products"],
["TYCO17 Index" , "Turkey Capacity Utilization Rate Manufacture Paper & Paper Products"],
["TYCO19 Index" , "Turkey Capacity Utilization Rate Manufacture Coke & Refined Petroleum Products"],
["TYCO21 Index" , "Turkey Capacity Utilization Rate Manufacture Basic Pharmaceutical Prdcts & Prep"],
["TYCO22 Index" , "Turkey Capacity Utilization Rate Manufacture Rubber & Plastic Products"],
["TYCO23 Index" , "Turkey Capacity Utilization Rate Manufact Other Non-Metal Mineral Products"],
["TYCO25 Index" , "Turkey Capacity Utilization Rate Manufacture Fabricated Metal Products"],
["TYCO26 Index" , "Turkey Capacity Utilization Rate Manufacture Computer Electronic & Optical Prod"],
["TYCO27 Index" , "Turkey Capacity Utilization Rate Manufacture Electrical Equipment"],
["TYCO29 Index" , "Turkey Capacity Utilization Rate Manufacture Motor Vehicle Trailer & SemiTrailer"],
["TYCO31 Index" , "Turkey Capacity Utilization Rate Manufacture Furniture"],
["TYCO32 Index" , "Turkey Capacity Utilization Rate Other Manufacturing"],
["TYCO33 Index" , "Turkey Capacity Utilization Rate Repair & Installation Machinery & Equipment"],
["TYCOMOM Index" , "Turkey Capacity Utilization MoM NSA"],
["TYCONZ CH Equity" , "Tycon Alloy Industries Shenzhen Co Ltd"],
["TYCONZ HK Equity" , "Tycon Alloy Industries Hong Kong Co Ltd"],
["TYCOOLD Index" , "Turkey Capacity Utilization Old Methodology"],
["TYCOYOY Index" , "Turkey Capacity Utilization YoY NSA"],
["0958855D US Equity" , "Tyco Fire & Security Services Korea Co Ltd"],
["0133350D US Equity" , "Tyco Integrated Security LLC"],
["AMP LI Equity" , "Tyco Electronics Corp (London Int'l)"],
["BL167972 Corp" , "Tycoons Group Enterprise Loan TWD REV B 03/10/2020"],
["TYCO ELE CDS USD SR 7Y D14 Corp" , "Tyco Electronics Group SA"],
["209 HK Equity" , "Winshine Science Co Ltd (Hong Kong)"],
["TYCEUR EU Equity" , "Tyco International Plc (European Composite)"],
["BL050458 Corp" , "TY Steel Loan USD REV B 02/22/2017"],
["0751500D LX Equity" , "Tyco International Holding Sarl"],
["0751503D US Equity" , "Tyco International Management LLC"],
["TYCN-R TB Equity" , "Tycoons Worldwide Group Thailand PCL (Bangkok)"],
["LHN GR Equity" , "Tyco International Plc (Germany)"],
["BL050457 Corp" , "TY Steel Loan USD TL A 02/22/2019"],
["TYC CDS USD SR 1Y D14 Corp" , "Tyco International Plc"],
["TYC-W US Equity" , "Tyco International Plc (U.S.)"],
["TYI QT Equity" , "Tyco International Plc (Quotrix Exchange)"],
["0533831D SW Equity" , "Tyco International Finance SA / Tyco International Ltd"],
["1162125D US Equity" , "Tyco International Finance SA/Tyco Fire & Security Finance SCA"],
["TYCN MM Equity" , "Tyco International Plc (Mexico)"],
["TYCSA CP Mmkt" , "Tyco International Group SA"],
["TYCO ELE CDS USD SR 6M D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 1Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 2Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 3Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 4Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 10Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 15Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 30Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 3M D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 6Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 8Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 9Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 11Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 12Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 20Y D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 0M D14 Corp" , "Tyco Electronics Group SA"],
["TYCO ELE CDS USD SR 9M D14 Corp" , "Tyco Electronics Group SA"],
["2022 TT Equity" , "Tycoons Group Enterprise (Taiwan Stock Exchange)"],
["0697046D US Equity" , "Tyco Flow Control Inc"],
["LHN1 TH Equity" , "Tyco International Plc (Tradegate)"],
["YCCD3169 Index" , "TYCO ELE CDS USD SR Curve"],
["1067Z LX Equity" , "Tyco International Group SA (Luxembourg)"],
["BL726473 Corp" , "Tyco Loan EUR TL A 06/30/2016"],
["MAT Pfd" , "Tyco Toys Inc"],
["TYC AR Equity" , "Tyco International Plc (Argentina)"],
["911622 TT Equity" , "Tycoons Worldwide Group Thailand PCL (Taiwan Stock Exchange)"],
["0194013D US Equity" , "Tyco Fire & Security LLC"],
["0593493D US Equity" , "Tyco International Management Co PAC (U.S.)"],
["0910232D HK Equity" , "Pacific Tycoon"],
["0129417D US Equity" , "Tyco Valves & Controls Inc"],
["BL726481 Corp" , "Tyco Loan EUR REV 06/30/2017"],
["BL779001 Corp" , "Tyco Loan EUR REV 12/31/2049"],
["TYCN/F TB Equity" , "Tycoons Worldwide Group Thailand PCL (Bangkok)"],
["0323731D TL Equity" , "Tyco Electronics Gibraltar Holding Ltd"],
["0824277D GR Equity" , "Tyco Fire & Security GmbH"],
["TYI GB Equity" , "Tyco International Plc (Berlin)"],
["TYI GR Equity" , "Tyco International Plc (Germany)"],
["5942A US Equity" , "Tyco Industries Inc (U.S.)"],
["TYCSA EMTN Mmkt" , "Tyco International Group SA"],
["TEL UN Equity" , "TE Connectivity Ltd (New York)"],
["BF050456 Corp" , "TY Steel Loan USD DEAL 02/22/2019"],
["BF167970 Corp" , "Tycoons Group Enterprise Loan TWD DEAL 03/10/2020"],
["BL167971 Corp" , "Tycoons Group Enterprise Loan TWD TL A-DD 03/10/2020"],
[".TYC 0 02/12/2021 Corp" , "PPCR: TYCO INTL GROUP"],
[".TYC 3.125 01/15/2008 Corp" , "PPCR: TYCO INTL GROUP"],
[".TYC 0 04/17/2021 100 Corp" , "PPCR: TYCO INTL GROUP"],
[".TYC 0 06/17/2021 Corp" , "PPCR: TYCO INTL GROUP"],
[".TYC 2.75 01/15/2018 Corp" , "PPCR: TYCO INTL GROUP"],
[".TYC 2.75 01/15/2018 001 Corp" , "PPCR: TYCO INTL GROUP"],
[".TYC 2.75 01/15/2018 1 Corp" , "PPCR: TYCO INTL GROUP"],
[".TYC 3.125 01/15/2023 Corp" , "PPCR: TYCO INTL GROUP"],
[".TYC 6.375 10/15/2011 Corp" , "PPCR: TYCO INTL GROUP"],
[".TYC 0 11/17/2020 Corp" , "PPCR: TYCO INTL LTD"],
[".TEL 1.1 03/01/2023 Corp" , "PPCR: TYCO ELECTRONICS"],
["0291489D AR Equity" , "Tyco Submarine Systems de Argentina SA"],
["7013301Z GR Equity" , "Tyco Electronics AMP GmbH"],
["BF065032 Corp" , "Tyco International Loan USD DEAL 08/07/2020"],
["BF193632 Corp" , "Tyco International Loan USD DEAL 03/07/2017"],
["BF193796 Corp" , "Tyco International Holding Loan USD DEAL 09/10/2019"],
["BF197339 Corp" , "Tyco International Loan USD DEAL 08/07/2020"],
["BF726469 Corp" , "Tyco Loan EUR DEAL 12/31/2049"],
["BF816853 Corp" , "TE Connectivity Loan USD DEAL 12/09/2020"],
["BL726477 Corp" , "Tyco Loan EUR TL B 06/30/2017"],
["TYC CDS USD SR 10Y D14 Corp" , "Tyco International Plc"],
["TYC CDS USD SR 2Y D14 Corp" , "Tyco International Plc"],
["TYC CDS USD SR 6Y D14 Corp" , "Tyco International Plc"],
["TYC CDS USD SR 7Y D14 Corp" , "Tyco International Plc"],
["TYC CDS USD SR 8Y D14 Corp" , "Tyco International Plc"],
["TYC CDS USD SR 9Y D14 Corp" , "Tyco International Plc"],
["MAT Corp" , "Tyco Toys Inc"],
["TYC LNST Mmkt" , "Tyco International Plc"],
["TYC=A OC Equity" , "Tyco International Plc Future (OneChicago)"],
["BVIS0275 Index" , "USD Tyco Electronics Group SA BVAL Yield Curve"],
["TYCD=A OC Equity" , "Tyco International Plc Dividend Neutral Future (OneChicago)"],
["0041099D US Equity" , "Tyco Valves & Controls LP"],
["0131052D US Equity" , "Tyco Safety Products US Inc"],
["0133587D CN Equity" , "Tyco Thermal Controls Canada Ltd"],
["0144541D CN Equity" , "Tyco Safety Products Canada Ltd"],
["0148692D CN Equity" , "Tyco International of Canada Ltd"],
["0157869D GR Equity" , "Tyco Electronics Raychem GmbH"],
["0161450D GR Equity" , "Tyco Thermal Controls Holding GmbH"],
["0164983D NA Equity" , "Tyco Building Services Products BV"],
["0169991D US Equity" , "Tyco Healthcare United States Surgical"],
["0173249D CH Equity" , "Tyco Fire & Security Beijing Co Ltd"],
["0173675D CH Equity" , "Tyco Thermal Controls Shanghai Trading Co Ltd"],
["0174650D CH Equity" , "Postech Tyco Electronic Nanjing Co Ltd"],
["0174985D CH Equity" , "Tyco Safety Products Shenyang Co Ltd"],
["0175003D CH Equity" , "Tyco Electronics Technology Kunshan Co Ltd"],
["TYC CDS USD SR 3Y D14 Corp" , "Tyco International Plc"],
["0177245D SP Equity" , "Tyco Flow Control Pte Ltd"],
["TYC CDS USD SR 3M D14 Corp" , "Tyco International Plc"],
["0177406D SP Equity" , "Tyco Fire & Building Products Asia Pte Ltd"],
["TYC CDS USD SR 6M D14 Corp" , "Tyco International Plc"],
["0177443D SP Equity" , "Tyco Fire Security & Services Pte Ltd"],
["TYC CDS USD SR 11Y D14 Corp" , "Tyco International Plc"],
["0179363D US Equity" , "Tyco Electrical & Metal Products"],
["TYC CDS USD SR 12Y D14 Corp" , "Tyco International Plc"],
["0180710D CH Equity" , "Tyco Electronics Shenzhen Co Ltd"],
["TYC CDS USD SR 15Y D14 Corp" , "Tyco International Plc"],
["0181028D CH Equity" , "Tyco Electronics Dongguan Ltd"],
["TYC CDS USD SR 20Y D14 Corp" , "Tyco International Plc"],
["0181430D HK Equity" , "Tyco Electronics HK Ltd"],
["TYC CDS USD SR 30Y D14 Corp" , "Tyco International Plc"],
["0183163D RU Equity" , "Tyco Electronics Rus OOO"],
["0189221D JP Equity" , "Tyco Healthcare Japan Inc"],
["TYC CDS USD SR 0M D14 Corp" , "Tyco International Plc"],
["0193383D US Equity" , "Tyco Electronics Installation Services Inc"],
["0198634D CB Equity" , "Tyco Services SA/Colombia"],
["TYC CDS USD SR 9M D14 Corp" , "Tyco International Plc"],
["0198661D CB Equity" , "Tyco Healthcare Colombia SA"],
["0202778D CI Equity" , "Tyco Services SA/Chile"],
["0219389D US Equity" , "Tyco Healthcare Group LP"],
["0224706D LN Equity" , "Tyco Electronics UK Holdings Ltd"],
["0240861D LN Equity" , "Tyco Flow Control UK Ltd"],
["0253003D FP Equity" , "Tyco Fire & Integrated Solutions France SASU"],
["0264054D CN Equity" , "Tyco Electronics Canada ULC"],
["0278536D AU Equity" , "Tyco Electronics Pty Ltd"],
["0278567D AU Equity" , "Tyco Projects Australia Pty Ltd"],
["0284957D MI Equity" , "CS Tyco Resolute Inc"],
["0286988D BH Equity" , "Tyco Global Networks Ltd"],
["0287079D BH Equity" , "Tyco Delta Ltd"],
["0287080D BH Equity" , "Tyco Beta Ltd"],
["0287081D BH Equity" , "Tyco Alpha Ltd"],
["0287083D BH Equity" , "Tyco Holdings Bermuda No 12 Ltd"],
["0287084D BH Equity" , "Tyco Kappa Ltd"],
["0288075D SP Equity" , "Tyco Pipe Systems Pte Ltd"],
["0288224D SP Equity" , "Tyco International Asia Inc/Singapore"],
["0290027D SP Equity" , "Tyco Water Asia"],
["0291864D ID Equity" , "Tyco Electronics Ireland Ltd"],
["0292048D ID Equity" , "Tyco International Finance Ireland"],
["0296269D DC Equity" , "Tyco Holding I Denmark ApS"],
["0296276D DC Equity" , "Tyco Electronics Far East Holdings ApS"],
["0296286D DC Equity" , "Tyco Holding VII Denmark ApS"],
["0296398D GR Equity" , "Tyco Electronics Germany Raychem GmbH & Co KG"],
["0296399D GR Equity" , "Tyco Electronics Germany AMP GmbH & Co KG"],
["0296657D GR Equity" , "Tyco International PLT Klartechnik GmbH"],
["0296685D GR Equity" , "Tyco Holding GmbH"],
["0296864D GR Equity" , "Tyco Electronics Holding GmbH"],
["0297112D GR Equity" , "Tyco International PLT GmbH"],
["0297558D GR Equity" , "Tyco Electronics Idento GmbH"],
["0297634D GR Equity" , "Tyco Umwelttechnik GmbH"],
["0302720D PW Equity" , "Tyco Fire & Integrated Solutions Sp zoo"],
["0305750D FP Equity" , "Tyco Networks France SASU"],
["0306784D LX Equity" , "Tyco Electronics Holding Sarl"],
["0307736D NA Equity" , "Tyco Networks Netherlands BV"],
["0308385D NA Equity" , "Tyco Electronics Netherlands Holding BV"],
["0311630D SW Equity" , "Tyco Plastics Services AG"],
["0311684D SW Equity" , "Tyco Flow Services AG"],
["0312305D SW Equity" , "Tyco International Finance Alpha GmbH"],
["0313156D SW Equity" , "Tyco Italy Switzerland GmbH"],
["0313157D SW Equity" , "Tyco China Switzerland GmbH"],
["0313167D SW Equity" , "Tyco Electronics Finance Alpha GmbH"],
["0313169D SW Equity" , "Tyco International Finance Group GmbH"],
["0313170D SW Equity" , "Tyco International Finance Holding GmbH"],
["0313231D SW Equity" , "Tyco Electronics Schweiz HFI 2 GmbH"],
["0313232D SW Equity" , "Tyco Electronics Schweiz Holding II GmbH"],
["0313337D SW Equity" , "Tyco International FH Switzerland GmbH"],
["0315096D NA Equity" , "Tyco International Fire and Security Holdings Cooperatief UA"],
["0315117D NA Equity" , "Tyco Electronics Netherlands Ireland Cooperatief UA"],
["0315120D NA Equity" , "Tyco Electronics Netherlands Italia Products BV"],
["0315122D NA Equity" , "Tyco Electronics Netherlands AMP Italia BV"],
["0315123D NA Equity" , "Tyco Electronics Netherlands PRS Canada BV"],
["0315155D NA Equity" , "Tyco Electronics Netherlands Canada BV"],
["0318886D GR Equity" , "Tyco Electronics Verwaltungs GmbH"],
["0320155D LN Equity" , "Tyco Electronics Holdings Ltd/United Kingdom"],
["0321243D CH Equity" , "Tyco Healthcare Trading Shanghai Co Ltd"],
["0321908D GR Equity" , "Tyco Electronics EC Verwaltungsgesellschaft GmbH"],
["0321918D GR Equity" , "Tyco Electronics Vermogensverwaltungs GmbH & Co KG"],
["0323492D MP Equity" , "Tyco Asia Investments Ltd"],
["0323696D MV Equity" , "Tyco Electronics Korea Malta Ltd"],
["0327664D SP Equity" , "Tyco EPG Pte Ltd"],
["0329173D SP Equity" , "Tyco Networks Singapore Pte Ltd"],
["0332607D MK Equity" , "Tyco Grinnell KM Sdn Bhd"],
["0333034D SP Equity" , "Tyco Electronics AMP Manufacturing S Pte Ltd"],
["0334675D HK Equity" , "Tyco Engineering & Construction Hong Kong Ltd"],
["0334817D HK Equity" , "Tyco Fire and Security Services China Ltd"],
["0335644D HK Equity" , "Tyco Networks Hong Kong Ltd"],
["0339068D HK Equity" , "Tyco Electronics Hong Kong Holdings No 1 Ltd"],
["0341965D PM Equity" , "Tyco Integrated Systems Philippines Inc"],
["0342116D PM Equity" , "Tyco Electronics Philippines Inc"],
["0342494D PM Equity" , "Tyco PIECO Corp Inc"],
["0347842D CH Equity" , "Tyco Electronics Qingdao Ltd"],
["0355866D AU Equity" , "Tyco Fire & Security Pty Ltd"],
["0356171D AU Equity" , "Tyco Flow Control Pacific Pty Ltd"],
["0356181D AU Equity" , "Tyco Australia Pty Ltd"],
["0356183D AU Equity" , "Tyco Healthcare Pty Ltd/Australia"],
["0356520D AU Equity" , "Tyco International Pty Ltd"],
["0380314D CH Equity" , "Tyco Water Valve Shanghai Co Ltd"],
["0380772D SM Equity" , "Tyco Integrated Fire & Security Corp Servicios SA"],
["0387721D CH Equity" , "Tyco Electronics AMP Qingdao Ltd"],
["0387762D CH Equity" , "Tyco Fire & Security Tianjin Ltd"],
["0387888D CH Equity" , "Tyco Electronics Kunshan Ltd"],
["0387945D CH Equity" , "Tyco Electronics Wuxi Ltd"],
["0388231D CH Equity" , "Tyco Electronics Zhuhai Ltd"],
["0388392D CH Equity" , "Tyco Electronics Suzhou Ltd"],
["0388515D CH Equity" , "Tyco Fire & Security Services International Trading Shanghai Co Ltd"],
["0388670D UH Equity" , "Tyco Fire & Security UAE-LLC"],
["0460055D GR Equity" , "Tyco Electronics Jordan GmbH & Co KG"],
["0493041D JP Equity" , "Tyco Fire Security Japanco Ltd"],
["0562812D US Equity" , "Tyco Ventures"],
["0575209D US Equity" , "Tyco Enterprises Inc"],
["0583448D US Equity" , "Tyco Electronics Corp PAC"],
["0587108D US Equity" , "Tyco Electronics Integrated Cable Systems LLC"],
["0603123D US Equity" , "Tyco International Plc (U.S.)"],
["0607277D US Equity" , "Tyco Worldwide Services Inc"],
["0607963D CN Equity" , "Tyco Healthcare Group Canada Inc"],
["0616177D LN Equity" , "Tyco Healthcare UK Pension Trustees Ltd"],
["0638705D IM Equity" , "Tyco Flow Control Italia Srl"],
["0639458D SS Equity" , "Tyco Electronics Svenska Holdings AB"],
["0668040D AU Equity" , "Tyco International Security Group Pty Ltd"],
["0672550D ID Equity" , "Tyco Packaging Ltd"],
["0677482D ID Equity" , "Tyco Healthcare"],
["0686146D KS Equity" , "Tyco Electronics AMP Korea Ltd"],
["0750532D US Equity" , "Tyco Electronics Services GmbH"],
["0801394D LN Equity" , "Tyco Toys UK Ltd"],
["0803363D US Equity" , "Tyco International Group SA Participation Certificate Trust"],
["0837000D US Equity" , "Tyco Fire Protection LLC"],
["0904051D US Equity" , "Tyco Federal Credit Union"],
["0944419D IM Equity" , "Tyco Electronics Italia Holding Srl"],
["0944715D NA Equity" , "Tyco Electronics Netherlands Canada Cooperatief UA"],
["0944886D NZ Equity" , "Tyco Healthcare Ltd/New Zealand"],
["0946375D CN Equity" , "Tyco Health Care Groupe Canada Inc"],
["0947329D BH Equity" , "Tyco Electronics Eta Ltd"],
["0947330D BH Equity" , "Tyco Electronics Lambda/Bermuda"],
["0948053D ID Equity" , "Raychem International/Ireland"],
["0953379D US Equity" , "Tyco Fire & Security Adt SE"],
["0953680D NA Equity" , "Tyco Labs Holland I BV"],
["0968352D US Equity" , "Tyco Valves & Controls - Puerto Rico Corp"],
["0992985D DC Equity" , "Tyco Electronics Denmark A/S"],
["1066794Z LN Equity" , "Tyco Healthcare UK Ltd"],
["1072114Z LN Equity" , "Tyco European Steel Strip Ltd"],
["1111335Z LN Equity" , "Tyco Fire Products Manufacturing Ltd"],
["1122863Z LN Equity" , "Tyco European Tubing Ltd"],
["1138087Z LN Equity" , "Tyco Building Services Products UK Ltd"],
["1150348D GR Equity" , "Tyco International Plc (Germany)"],
["1170997D IM Equity" , "Tyco Fire & Security SpA"],
["1187631Z LN Equity" , "Tyco European Metal Framing Ltd"],
["1187847Z LN Equity" , "Tyco Thermal Controls UK Ltd"],
["1197117D US Equity" , "Tyco Electronics Defined Benefit Plans Master Trust"],
["1202247Z NA Equity" , "Tyco Integrated Systems BV"],
["1203351Z LN Equity" , "Tyco Healthcare UK Manufacturing Ltd"],
["1244066D SW Equity" , "Tyco International Services Holding GmbH"],
["1244131D SW Equity" , "Tyco-ADT Security Services AG"],
["1266223Z LN Equity" , "Tyco Valves & Controls Distribution UK Ltd"],
["1353371D US Equity" , "Tyco Healthcare Retail Group Inc"],
["1354033D US Equity" , "Tyco Electronics US Inc"],
["1356002D US Equity" , "Tyco Electronics Printed Circuit Group LP"],
["1358501D CN Equity" , "Tyco Integrated Security Canada Inc"],
["1359708D MK Equity" , "Tyco Healthcare Medical Supplies Sdn Bhd"],
["1360095D LN Equity" , "Tyco Electronics Components Ltd"],
["1506586Z LN Equity" , "Tyco Fire & Integrated Solutions UK Ltd"],
["1639896Z LN Equity" , "Tyco Valves Ltd"],
["1712Q US Equity" , "Tyco Toys Inc (U.S.)"],
["1789801Z LN Equity" , "Mattel Tyco UK Ltd"],
["1823Q US Equity" , "Tyco International US Inc (U.S.)"],
["1853738Z LN Equity" , "Tyco Engineered Products UK Ltd"],
["1881046Z LN Equity" , "Tyco Electronics Motors Ltd"],
["2335265Z SM Equity" , "Tyco Electronics AMP Espana SAU"],
["2344123Z LN Equity" , "Tyco Integrated Systems Ltd"],
["252110Q AU Equity" , "Tyco Invests (Aust) Ltd (Australia)"],
["2771784Z LN Equity" , "Tyco Electronics VI"],
["2925586Z LN Equity" , "Tyco Electronics UK Ltd"],
["298199Z US Equity" , "Tyco Telecommunications US Inc"],
["3632899Z SM Equity" , "Tyco Integrated Security SL"],
["3632987Z PL Equity" , "Tyco Electronics Componentes Electromecanicos Lda"],
["3632995Z FP Equity" , "Tyco Electronics France SAS"],
["3633003Z NA Equity" , "Tyco Energy Valves BV"],
["3633011Z US Equity" , "Tyco Fire Products LP"],
["3633019Z NO Equity" , "Tyco Networks Norway AS"],
["3633027Z BB Equity" , "Tyco Thermal Controls NV"],
["3895334Z NA Equity" , "Tyco Electronics Wireless Systems BV"],
["3895398Z BB Equity" , "Tyco Adhesives BVBA"],
["3895406Z NA Equity" , "Tyco Electronics Nederland BV"],
["3895414Z SS Equity" , "Tyco Electronics Svenska AB"],
["3898770Z NA Equity" , "Tyco Fire & Security Nederland BV"],
["3901274Z BB Equity" , "Tyco Fire & Integrated Solutions NV"],
["398947Z LN Equity" , "Tyco UK Metals"],
["398987Z US Equity" , "Tyco Global Network"],
["4491267Z IM Equity" , "Tyco Electronics AMP Italia Srl"],
["4513999Z LN Equity" , "Tyco Electronics UK Infrastructure Ltd"],
["4524303Z IM Equity" , "Tyco Valves and Controls Italia Srl"],
["4524311Z FP Equity" , "Tyco Thermal Controls SA"],
["4524319Z ID Equity" , "Tyco Healthcare Ireland Ltd"],
["4524327Z FP Equity" , "Tyco Electronics SIMEL SAS"],
["4524335Z AV Equity" , "Tyco Electronics Raychem BVBA"],
["4524343Z AV Equity" , "Tyco Electronics Belgium EC BVBA"],
["4524351Z IM Equity" , "Tyco Electronics AMP Italia Products SRL"],
["4524359Z FP Equity" , "Tyco Building Services Products SAS"],
["4524367Z IM Equity" , "Tyco Building Services Products Italy Srl"],
["51200Z LN Equity" , "Tyco Holdings UK Ltd"],
["6140519Z MM Equity" , "Tyco Electronics Power Systems de Mexico SA de CV"],
["6596484Z IN Equity" , "Tyco SAnmar Ltd"],
["6824161Z AV Equity" , "Tyco Electronics Austria GmbH"],
["6824169Z AV Equity" , "Tyco Fire & Integrated Solutions GmbH"],
["6845137Z SM Equity" , "Tyco Electronics Raychem SA"],
["6845145Z SM Equity" , "Tyco Marine SA"],
["6867493Z CN Equity" , "Tyco Valves & Controls Canada Inc"],
["6909253Z NZ Equity" , "Tyco Electronics NZ Ltd"],
["6909261Z NZ Equity" , "Tyco New Zealand Ltd"],
["6919677Z AU Equity" , "Tyco Electronics Energy Pty Ltd"],
["6932861Z MK Equity" , "Tyco Fire Security & Services Malaysia Sdn Bhd"],
["6940025Z SP Equity" , "Tyco Electronics Manufacturing Singapore Pte Ltd"],
["6940033Z SP Equity" , "Tyco Electronics Singapore Pte Ltd"],
["6964345Z MM Equity" , "Tyco Electronics Mexico SA"],
["6975649Z CB Equity" , "Tyco Electronics Colombia Ltda"],
["6976481Z BZ Equity" , "Tyco Valves & Controls Brasil Ltda"],
["6984401Z AR Equity" , "Tyco Electronics Argentina SA"],
["6984409Z AR Equity" , "Tyco Flow Control Argentina SA"],
["6998241Z CP Equity" , "Tyco Electronics Czech sro"],
["6998249Z CP Equity" , "Tyco Electronics EC Trutnov sro"],
["6998257Z CP Equity" , "Tyco Fire & Integrated Solutions sro"],
["7013293Z GR Equity" , "Tyco Building Services Products Germany GmbH"],
["7013317Z GR Equity" , "Tyco Thermal Controls GmbH"],
["7013325Z GR Equity" , "Tyco Valves & Controls Distribution GmbH"],
["7158509Z PW Equity" , "TYCO Electronics Polska Sp zoo"],
["7172689Z IN Equity" , "Tyco Electronics Corp India Pvt Ltd"],
["7172697Z IN Equity" , "Tyco Electronics Systems India Pvt Ltd"],
["7256705Z HB Equity" , "Tyco Electronics Hungary Termelo Kft"],
["7278313Z SS Equity" , "Tyco Fire & Integrated Solutions Sweden AB"],
["7396671Z FP Equity" , "Tyco Valves Controls Distrfrance"],
["7704423Z SW Equity" , "Tyco Fire & Integrated Solutions Schweiz AG"],
["7707383Z SS Equity" , "Tyco Building Services Products Sweden AB"],
["7710367Z NO Equity" , "Tyco Building Services Products Norway AS"],
["7723472Z NZ Equity" , "Tyco Flow Control Pacific Pty Ltd/New Zealand"],
["7729072Z MK Equity" , "Tyco Electronics Malaysia Sdn Bhd"],
["7729080Z MK Equity" , "Tyco Flow Control Malaysia Sdn Bhd"],
["774489Z US Equity" , "Tyco Printed Circuit Group LP"],
["7746380Z IN Equity" , "Tyco Engineering & Construction Pvt Ltd"],
["8366787Z TB Equity" , "Tyco Fire Security & Services Thailand Ltd"],
["9023641Z NO Equity" , "Tyco Thermal Controls Norway AS"],
["9155459Z IN Equity" , "Tyco Fire & Security India Pvt Ltd"],
["9215505Z US Equity" , "Tyco Retail Solutions"],
["9661947Z US Equity" , "Tyco Electronics Integrated"],
["9786794Z US Equity" , "Tyco International Inc/Menlo Park"],
["ABFDJZ KS Equity" , "Tyco Marine Services Korea Co Ltd"],
["ABGAFZ JP Equity" , "Tyco Flow Control Japan Co Ltd"],
["ADF/A CN Equity" , "Tyco Integrated Security Finance Inc (Canada)"],
["LHN1 GR Equity" , "Tyco International Plc (Germany)"],
["QUNTYC AU Equity" , "Tyco International Plc (Australia)"],
["TGCOEZ CH Equity" , "Tyco Electronics Technology SIP Ltd"],
["TYC AF Equity" , "Tyco International Plc (Buenos Floor)"],
["TYC AS Equity" , "Tyco International Plc (Buenos Sinac)"],
["TYC UB Equity" , "Tyco International Plc (NASDAQ OMX BX)"],
["TYC UC Equity" , "Tyco International Plc (National Stock Exchange)"],
["TYC UD Equity" , "Tyco International Plc (FINRA ADF)"],
["TYC UF Equity" , "Tyco International Plc (BATS)"],
["TYC UM Equity" , "Tyco International Plc (Chicago)"],
["TYC UP Equity" , "Tyco International Plc (NYSE Arca)"],
["TYC UT Equity" , "Tyco International Plc (NASDAQ InterMarket)"],
["TYC UX Equity" , "Tyco International Plc (NASDAQ OMX PSX)"],
["TYC VJ Equity" , "Tyco International Plc (EDGA)"],
["TYC VK Equity" , "Tyco International Plc (EDGX)"],
["TYC VY Equity" , "Tyco International Plc (BATS Y)"],
["TYCC AF Equity" , "Tyco International Plc (Buenos Floor)"],
["TYCC AR Equity" , "Tyco International Plc (Argentina)"],
["TYCC AS Equity" , "Tyco International Plc (Buenos Sinac)"],
["TYCD AF Equity" , "Tyco International Plc (Buenos Floor)"],
["TYCD AR Equity" , "Tyco International Plc (Argentina)"],
["TYCD AS Equity" , "Tyco International Plc (Buenos Sinac)"],
["TYCEUR E1 Equity" , "Tyco International Plc (Euro OTC)"],
["TYCEUR EO Equity" , "Tyco International Plc (OTC Composite)"],
["TYCEUR XA Equity" , "Tyco International Plc (CEESEG OTC and LJSE Block Trades)"],
["TYCEUR XB Equity" , "Tyco International Plc (BOAT)"],
["TYCEUR XD Equity" , "Tyco International Plc (Deutsche Boerse OTC)"],
["TYCEUR XE Equity" , "Tyco International Plc (Euronext OTC)"],
["TYCEUR XF Equity" , "Tyco International Plc (Dublin SE OTC)"],
["TYCEUR XG Equity" , "Tyco International Plc (Nordic Growth Market OTC)"],
["TYCEUR XH Equity" , "Tyco International Plc (Budapest SE OTC)"],
["TYCEUR XI Equity" , "Tyco International Plc (Borsa Italia SE OTC)"],
["TYCEUR XJ Equity" , "Tyco International Plc (Ljubljana SE OTC)"],
["TYCEUR XL Equity" , "Tyco International Plc (London SE OTC)"],
["TYCEUR XN Equity" , "Tyco International Plc (Oslo OTC)"],
["TYCEUR XO Equity" , "Tyco International Plc (OMX OTC)"],
["TYCEUR XP Equity" , "Tyco International Plc (Plus Markets OTC)"],
["TYCEUR XS Equity" , "Tyco International Plc (Stuttgart OTC)"],
["TYCEUR XT Equity" , "Tyco International Plc (Athens OTC)"],
["TYCEUR XU Equity" , "Tyco International Plc (Bulgaria Stock Exchange OTC)"],
["TYCEUR XV Equity" , "Tyco International Plc (BATS Chi-X OTC)"],
["TYCEUR XW Equity" , "Tyco International Plc (SIX Off-Order-Book)"],
["TYCP ECP Mmkt" , "Tyco International Group SA"],
["TYCPA AU Equity" , "Tyco Invests (Aust) Ltd (Australia)"],
["TYI GD Equity" , "Tyco International Plc (Dusseldorf)"],
["TYI GF Equity" , "Tyco International Plc (Frankfurt)"],
["TYI GH Equity" , "Tyco International Plc (Hamburg)"],
["TYI GM Equity" , "Tyco International Plc (Munich)"],
["TYI GS Equity" , "Tyco International Plc (Stuttgart)"],
["TYIVF US Equity" , "Tyco Invests (Aust) Ltd (U.S.)"],
["TYRROZ CH Equity" , "Tyco Electronics AMP Shanghai Ltd"],
["TYSREZ JP Equity" , "Tyco Electronics Kogyo KK"],
["TYC=1 OC Equity" , "Tyco International Plc 1st Generic Future (OneChicago)"],
["TYC=2 OC Equity" , "Tyco International Plc 2nd Generic Future (OneChicago)"],
["TYC=3 OC Equity" , "Tyco International Plc 3rd Generic Future (OneChicago)"],
["TYC=4 OC Equity" , "Tyco International Plc 4th Generic Future (OneChicago)"],
["TYC=J6 OC Equity" , "Tyco International Plc Apr 2016 Future (OneChicago)"],
["TYC=K6 OC Equity" , "Tyco International Plc May 2016 Future (OneChicago)"],
["TYC=M6 OC Equity" , "Tyco International Plc Jun 2016 Future (OneChicago)"],
["TYC=U6 OC Equity" , "Tyco International Plc Sep 2016 Future (OneChicago)"],
["TYCD=1 OC Equity" , "Tyco International Plc 1st Generic Dividend Neutral Future (OneChicago)"],
["TYCD=2 OC Equity" , "Tyco International Plc 2nd Generic Dividend Neutral Future (OneChicago)"],
["TYCD=3 OC Equity" , "Tyco International Plc 3rd Generic Dividend Neutral Future (OneChicago)"],
["TYCD=4 OC Equity" , "Tyco International Plc 4th Generic Dividend Neutral Future (OneChicago)"],
["TYCD=J6 OC Equity" , "Tyco International Plc Apr 2016 Dividend Neutral Future (OneChicago)"],
["TYCD=K6 OC Equity" , "Tyco International Plc May 2016 Dividend Neutral Future (OneChicago)"],
["TYCD=M6 OC Equity" , "Tyco International Plc Jun 2016 Dividend Neutral Future (OneChicago)"],
["TYCD=U6 OC Equity" , "Tyco International Plc Sep 2016 Dividend Neutral Future (OneChicago)"],
["TYA Cmdty" , "US Treasury Note, 10Yr Active Contract"],
["TYA IM Equity" , "Toscana Aeroporti SpA (Borsa Italiana)"],
["TYAISP Cmdty" , "TYA Invoice Spread"],
["TYAFWD Cmdty" , "TYA Fwd Yield"],
["TYA VN Equity" , "Taya Vietnam Electric Wire and Cable JSC (Vietnam)"],
["TYAISPO Cmdty" , "TYA Invoice Spread OIS"],
["TYAH6 Cmdty" , "Diesel, 10ppm CIF NWE Mar16"],
["TYM6 Cmdty" , "US Treasury Note, 10Yr Jun16"],
["TYA1 Cmdty" , "Generic 1st Diesel, 10ppm CIF NWE"],
["TYAU5 Cmdty" , "Diesel, 10ppm CIF NWE Sep15"],
["TYABY US Equity" , "Turkiye Is Bankasi (U.S.)"],
["TYAWSLE AU Equity" , "Nikko AM-Tyndall Australian Share Wholesale Fund (Australia)"],
["TYAA Cmdty" , "Diesel, 10ppm CIF NWE Active Contract"],
["TYAJ6 Cmdty" , "Diesel, 10ppm CIF NWE Apr16"],
["TY1 Cmdty" , "Generic 1st US Treasury Note, 10Yr"],
["TYABF US Equity" , "Turkiye Is Bankasi (U.S.)"],
["TYA CN Equity" , "Tygas Resource Corp (Canada)"],
["TYA EU Equity" , "Toscana Aeroporti SpA (European Composite)"],
["TYA AU Equity" , "Asteron Ltd (Australia)"],
["TYA E1 Equity" , "Toscana Aeroporti SpA (Euro OTC)"],
["TYA EO Equity" , "Toscana Aeroporti SpA (OTC Composite)"],
["TYA GR Equity" , "Toyama Chemical Co Ltd (Germany)"],
["TYA IC Equity" , "Toscana Aeroporti SpA (Milan Comp Day)"],
["TYA NZ Equity" , "Asteron Ltd (NZX)"],
["TYA VM Equity" , "Taya Vietnam Electric Wire and Cable JSC (Ho Chi Minh)"],
["TYA XA Equity" , "Toscana Aeroporti SpA (CEESEG OTC and LJSE Block Trades)"],
["TYA XB Equity" , "Toscana Aeroporti SpA (BOAT)"],
["TYA XC Equity" , "Toscana Aeroporti SpA (Chi-X OTC)"],
["TYA XD Equity" , "Toscana Aeroporti SpA (Deutsche Boerse OTC)"],
["TYA XE Equity" , "Toscana Aeroporti SpA (Euronext OTC)"],
["TYA XF Equity" , "Toscana Aeroporti SpA (Dublin SE OTC)"],
["TYA XG Equity" , "Toscana Aeroporti SpA (Nordic Growth Market OTC)"],
["TYA XH Equity" , "Toscana Aeroporti SpA (Budapest SE OTC)"],
["TYA XI Equity" , "Toscana Aeroporti SpA (Borsa Italia SE OTC)"],
["TYA XJ Equity" , "Toscana Aeroporti SpA (Ljubljana SE OTC)"],
["TYA XL Equity" , "Toscana Aeroporti SpA (London SE OTC)"],
["TYA XN Equity" , "Toscana Aeroporti SpA (Oslo OTC)"],
["TYA XO Equity" , "Toscana Aeroporti SpA (OMX OTC)"],
["TYA XP Equity" , "Toscana Aeroporti SpA (Plus Markets OTC)"],
["TYA XS Equity" , "Toscana Aeroporti SpA (Stuttgart OTC)"],
["TYA XT Equity" , "Toscana Aeroporti SpA (Athens OTC)"],
["TYA XV Equity" , "Toscana Aeroporti SpA (BATS Chi-X OTC)"],
["TYA XW Equity" , "Toscana Aeroporti SpA (SIX Off-Order-Book)"],
["TY MAY16 50D VOL BVOL Cmdty" , "May 2016 50 Delta Implied Volatility for TY(TYA)"],
["TYA6 Cmdty" , "Generic 6th Diesel, 10ppm CIF NWE"],
["TYASITS AU Equity" , "Phillips Special Situations Fund (Australia)"],
["TYAN7 Cmdty" , "Diesel, 10ppm CIF NWE Jul17"],
["TY 2M 50D VOL BVOL Cmdty" , "2 Month 50 Delta Implied Volatility for TY(TYA)"],
["TY APR16 50D VOL BVOL Cmdty" , "April 2016 50 Delta Implied Volatility for TY(TYA)"],
["TYASVAL AU Equity" , "Nikko AM-Tyndall Australian Share Value Fund (Australia)"],
["TY 1M 100 VOL BVOL Cmdty" , "1 Month 100 % Moneyness Implied Volatility for TY(TYA)"],
["TYH6 Cmdty" , "US Treasury Note, 10Yr Mar16"],
["TY JUN16 50D VOL BVOL Cmdty" , "June 2016 50 Delta Implied Volatility for TY(TYA)"],
["TYAG7 Cmdty" , "Diesel, 10ppm CIF NWE Feb17"],
["TYAM6 Cmdty" , "Diesel, 10ppm CIF NWE Jun16"],
["TYAUSTS AU Equity" , "Nikko AM-Tyndall Australian Share Fund (Australia)"],
["TY 1M 25DC VOL BVOL Cmdty" , "1 Month 25 Delta Call Implied Volatility for TY(TYA)"],
["TYAG6 Cmdty" , "Diesel, 10ppm CIF NWE Feb16"],
["URAMP RU Equity" , "Uralmashplant OJSC (Russia)"],
["TY 1M 25DP VOL BVOL Cmdty" , "1 Month 25 Delta Put Implied Volatility for TY(TYA)"],
["TY 1M 50D VOL BVOL Cmdty" , "1 Month 50 Delta Implied Volatility for TY(TYA)"],
["TY 3M 100 VOL BVOL Cmdty" , "3 Month 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY 3M 102.5 VOL BVOL Cmdty" , "3 Month 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TYABA AU Equity" , "Asteron Ltd (Australia)"],
["TYABB AU Equity" , "Asteron Ltd (Australia)"],
["TYABC AU Equity" , "Asteron Ltd (Australia)"],
["TYABN AU Equity" , "Asteron Ltd (Australia)"],
["TYABS Corp" , "TY Securitization Specialty Co Ltd (Multiple Matches)"],
["TYABY PQ Equity" , "Turkiye Is Bankasi (OTC Markets)"],
["TYABY UV Equity" , "Turkiye Is Bankasi (OTC US)"],
["TYACLZ CH Equity" , "Tianjin Yanyu Asset Co Ltd"],
["TYAFZ JP Equity" , "Taiyo A&F Co Ltd"],
["TYAHF US Equity" , "Tsuchiya Holdings Co Ltd (U.S.)"],
["TYAIDZ JP Equity" , "Toyo Aerosol Industry Co Ltd"],
["TYALF US Equity" , "Toyo Aluminium KK (U.S.)"],
["TYALPH Corp" , "TY Alpha City Securitization Specialty Co Ltd"],
["TYAM B3 Equity" , "Toscana Aeroporti SpA (Blockmatch)"],
["TYAM EB Equity" , "Toscana Aeroporti SpA (BATS Europe)"],
["TYAM IX Equity" , "Toscana Aeroporti SpA (Chi-X Europe)"],
["TYAM L3 Equity" , "Toscana Aeroporti SpA (Liquidnet)"],
["TYAM PO Equity" , "Toscana Aeroporti SpA (ITG Posit)"],
["TYAM S2 Equity" , "Toscana Aeroporti SpA (UBS MTF)"],
["TYAM TQ Equity" , "Toscana Aeroporti SpA (Turquoise)"],
["TYAN AU Equity" , "Asteron Ltd (Australia)"],
["TYANB AU Equity" , "Asteron Ltd (Australia)"],
["TYANC AU Equity" , "Asteron Ltd (Australia)"],
["TYANGC TWCP Mmkt" , "Tung Yang Chemical Co Ltd"],
["TYAOF US Equity" , "Toyo Asano Foundation Co Ltd (U.S.)"],
["TYARA AU Equity" , "Asteron Ltd (Australia)"],
["TYARB AU Equity" , "Asteron Ltd (Australia)"],
["TYASKZ JP Equity" , "Toyamaken Shinyo Kumiai"],
["TYAU6 Cmdty" , "Diesel, 10ppm CIF NWE Sep16"],
["TYAV6 Cmdty" , "Diesel, 10ppm CIF NWE Oct16"],
["TYAVF US Equity" , "UTair Aviation PJSC (U.S.)"],
["TYAVY US Equity" , "UTair Aviation PJSC (U.S.)"],
["TYAZ6 Cmdty" , "Diesel, 10ppm CIF NWE Dec16"],
["TYA10 Cmdty" , "Generic 10th Diesel, 10ppm CIF NWE"],
["TYA11 Cmdty" , "Generic 11st Diesel, 10ppm CIF NWE"],
["TYA12 Cmdty" , "Generic 12nd Diesel, 10ppm CIF NWE"],
["TYA13 Cmdty" , "Generic 13rd Diesel, 10ppm CIF NWE"],
["TYA14 Cmdty" , "Generic 14th Diesel, 10ppm CIF NWE"],
["TYA15 Cmdty" , "Generic 15th Diesel, 10ppm CIF NWE"],
["TYA16 Cmdty" , "Generic 16th Diesel, 10ppm CIF NWE"],
["TYA17 Cmdty" , "Generic 17th Diesel, 10ppm CIF NWE"],
["TYA18 Cmdty" , "Generic 18th Diesel, 10ppm CIF NWE"],
["TYA19 Cmdty" , "Generic 19th Diesel, 10ppm CIF NWE"],
["TYA2 Cmdty" , "Generic 2nd Diesel, 10ppm CIF NWE"],
["TYA20 Cmdty" , "Generic 20th Diesel, 10ppm CIF NWE"],
["TYA21 Cmdty" , "Generic 21st Diesel, 10ppm CIF NWE"],
["TYA22 Cmdty" , "Generic 22nd Diesel, 10ppm CIF NWE"],
["TYA23 Cmdty" , "Generic 23rd Diesel, 10ppm CIF NWE"],
["TYA24 Cmdty" , "Generic 24th Diesel, 10ppm CIF NWE"],
["TYA25 Cmdty" , "Generic 25th Diesel, 10ppm CIF NWE"],
["TYA26 Cmdty" , "Generic 26th Diesel, 10ppm CIF NWE"],
["TYA27 Cmdty" , "Generic 27th Diesel, 10ppm CIF NWE"],
["TYA28 Cmdty" , "Generic 28th Diesel, 10ppm CIF NWE"],
["TYA29 Cmdty" , "Generic 29th Diesel, 10ppm CIF NWE"],
["TYA3 Cmdty" , "Generic 3rd Diesel, 10ppm CIF NWE"],
["TYA30 Cmdty" , "Generic 30th Diesel, 10ppm CIF NWE"],
["TYA31 Cmdty" , "Generic 31st Diesel, 10ppm CIF NWE"],
["TYA32 Cmdty" , "Generic 32nd Diesel, 10ppm CIF NWE"],
["TYA33 Cmdty" , "Generic 33rd Diesel, 10ppm CIF NWE"],
["TYA34 Cmdty" , "Generic 34th Diesel, 10ppm CIF NWE"],
["TYA35 Cmdty" , "Generic 35th Diesel, 10ppm CIF NWE"],
["TYA36 Cmdty" , "Generic 36th Diesel, 10ppm CIF NWE"],
["TYA4 Cmdty" , "Generic 4th Diesel, 10ppm CIF NWE"],
["TYA5 Cmdty" , "Generic 5th Diesel, 10ppm CIF NWE"],
["TYA7 Cmdty" , "Generic 7th Diesel, 10ppm CIF NWE"],
["TYA8 Cmdty" , "Generic 8th Diesel, 10ppm CIF NWE"],
["TYA9 Cmdty" , "Generic 9th Diesel, 10ppm CIF NWE"],
["TYAF09 Cmdty" , "Diesel, 10ppm CIF NWE Jan09"],
["TYAF10 Cmdty" , "Diesel, 10ppm CIF NWE Jan10"],
["TYAF11 Cmdty" , "Diesel, 10ppm CIF NWE Jan11"],
["TYAF12 Cmdty" , "Diesel, 10ppm CIF NWE Jan12"],
["TYAF13 Cmdty" , "Diesel, 10ppm CIF NWE Jan13"],
["TYAF14 Cmdty" , "Diesel, 10ppm CIF NWE Jan14"],
["TYAF15 Cmdty" , "Diesel, 10ppm CIF NWE Jan15"],
["TYAF6 Cmdty" , "Diesel, 10ppm CIF NWE Jan16"],
["TYAF7 Cmdty" , "Diesel, 10ppm CIF NWE Jan17"],
["TYAF8 Cmdty" , "Diesel, 10ppm CIF NWE Jan18"],
["TYAF9 Cmdty" , "Diesel, 10ppm CIF NWE Jan19"],
["TYAG09 Cmdty" , "Diesel, 10ppm CIF NWE Feb09"],
["TYAG10 Cmdty" , "Diesel, 10ppm CIF NWE Feb10"],
["TYAG11 Cmdty" , "Diesel, 10ppm CIF NWE Feb11"],
["TYAG12 Cmdty" , "Diesel, 10ppm CIF NWE Feb12"],
["TYAG13 Cmdty" , "Diesel, 10ppm CIF NWE Feb13"],
["TYAG14 Cmdty" , "Diesel, 10ppm CIF NWE Feb14"],
["TYAG15 Cmdty" , "Diesel, 10ppm CIF NWE Feb15"],
["TYAG8 Cmdty" , "Diesel, 10ppm CIF NWE Feb18"],
["TYAG9 Cmdty" , "Diesel, 10ppm CIF NWE Feb19"],
["TYAGV Cmdty" , "TY AGGREGATE VOLUME"],
["TYAH09 Cmdty" , "Diesel, 10ppm CIF NWE Mar09"],
["TYAH10 Cmdty" , "Diesel, 10ppm CIF NWE Mar10"],
["TYAH11 Cmdty" , "Diesel, 10ppm CIF NWE Mar11"],
["TYAH12 Cmdty" , "Diesel, 10ppm CIF NWE Mar12"],
["TYAH13 Cmdty" , "Diesel, 10ppm CIF NWE Mar13"],
["TYAH14 Cmdty" , "Diesel, 10ppm CIF NWE Mar14"],
["TYAH15 Cmdty" , "Diesel, 10ppm CIF NWE Mar15"],
["TYAH7 Cmdty" , "Diesel, 10ppm CIF NWE Mar17"],
["TYAH8 Cmdty" , "Diesel, 10ppm CIF NWE Mar18"],
["TYAH9 Cmdty" , "Diesel, 10ppm CIF NWE Mar19"],
["TYAJ08 Cmdty" , "Diesel, 10ppm CIF NWE Apr08"],
["TYAJ09 Cmdty" , "Diesel, 10ppm CIF NWE Apr09"],
["TYAJ10 Cmdty" , "Diesel, 10ppm CIF NWE Apr10"],
["TYAJ11 Cmdty" , "Diesel, 10ppm CIF NWE Apr11"],
["TYAJ12 Cmdty" , "Diesel, 10ppm CIF NWE Apr12"],
["TYAJ13 Cmdty" , "Diesel, 10ppm CIF NWE Apr13"],
["TYAJ14 Cmdty" , "Diesel, 10ppm CIF NWE Apr14"],
["TYAJ15 Cmdty" , "Diesel, 10ppm CIF NWE Apr15"],
["TYAJ7 Cmdty" , "Diesel, 10ppm CIF NWE Apr17"],
["TYAJ8 Cmdty" , "Diesel, 10ppm CIF NWE Apr18"],
["TYAK08 Cmdty" , "Diesel, 10ppm CIF NWE May08"],
["TYAK09 Cmdty" , "Diesel, 10ppm CIF NWE May09"],
["TYAK10 Cmdty" , "Diesel, 10ppm CIF NWE May10"],
["TYAK11 Cmdty" , "Diesel, 10ppm CIF NWE May11"],
["TYAK12 Cmdty" , "Diesel, 10ppm CIF NWE May12"],
["TYAK13 Cmdty" , "Diesel, 10ppm CIF NWE May13"],
["TYAK14 Cmdty" , "Diesel, 10ppm CIF NWE May14"],
["TYAK5 Cmdty" , "Diesel, 10ppm CIF NWE May15"],
["TYAK6 Cmdty" , "Diesel, 10ppm CIF NWE May16"],
["TYAK7 Cmdty" , "Diesel, 10ppm CIF NWE May17"],
["TYAK8 Cmdty" , "Diesel, 10ppm CIF NWE May18"],
["TYAM08 Cmdty" , "Diesel, 10ppm CIF NWE Jun08"],
["TYAM09 Cmdty" , "Diesel, 10ppm CIF NWE Jun09"],
["TYAM10 Cmdty" , "Diesel, 10ppm CIF NWE Jun10"],
["TYAM11 Cmdty" , "Diesel, 10ppm CIF NWE Jun11"],
["TYAM12 Cmdty" , "Diesel, 10ppm CIF NWE Jun12"],
["TYAM13 Cmdty" , "Diesel, 10ppm CIF NWE Jun13"],
["TYAM14 Cmdty" , "Diesel, 10ppm CIF NWE Jun14"],
["TYAM5 Cmdty" , "Diesel, 10ppm CIF NWE Jun15"],
["TYAM7 Cmdty" , "Diesel, 10ppm CIF NWE Jun17"],
["TYAM8 Cmdty" , "Diesel, 10ppm CIF NWE Jun18"],
["TYAN08 Cmdty" , "Diesel, 10ppm CIF NWE Jul08"],
["TYAN09 Cmdty" , "Diesel, 10ppm CIF NWE Jul09"],
["TYAN10 Cmdty" , "Diesel, 10ppm CIF NWE Jul10"],
["TYAN11 Cmdty" , "Diesel, 10ppm CIF NWE Jul11"],
["TYAN12 Cmdty" , "Diesel, 10ppm CIF NWE Jul12"],
["TYAN13 Cmdty" , "Diesel, 10ppm CIF NWE Jul13"],
["TYAN14 Cmdty" , "Diesel, 10ppm CIF NWE Jul14"],
["TYAN5 Cmdty" , "Diesel, 10ppm CIF NWE Jul15"],
["TYAN6 Cmdty" , "Diesel, 10ppm CIF NWE Jul16"],
["TYAN8 Cmdty" , "Diesel, 10ppm CIF NWE Jul18"],
["TYAQ08 Cmdty" , "Diesel, 10ppm CIF NWE Aug08"],
["TYAQ09 Cmdty" , "Diesel, 10ppm CIF NWE Aug09"],
["TYAQ10 Cmdty" , "Diesel, 10ppm CIF NWE Aug10"],
["TYAQ11 Cmdty" , "Diesel, 10ppm CIF NWE Aug11"],
["TYAQ12 Cmdty" , "Diesel, 10ppm CIF NWE Aug12"],
["TYAQ13 Cmdty" , "Diesel, 10ppm CIF NWE Aug13"],
["TYAQ14 Cmdty" , "Diesel, 10ppm CIF NWE Aug14"],
["TYAQ5 Cmdty" , "Diesel, 10ppm CIF NWE Aug15"],
["TYAQ6 Cmdty" , "Diesel, 10ppm CIF NWE Aug16"],
["TYAQ7 Cmdty" , "Diesel, 10ppm CIF NWE Aug17"],
["TYAQ8 Cmdty" , "Diesel, 10ppm CIF NWE Aug18"],
["TYAU08 Cmdty" , "Diesel, 10ppm CIF NWE Sep08"],
["TYAU09 Cmdty" , "Diesel, 10ppm CIF NWE Sep09"],
["TYAU10 Cmdty" , "Diesel, 10ppm CIF NWE Sep10"],
["TYAU11 Cmdty" , "Diesel, 10ppm CIF NWE Sep11"],
["TYAU12 Cmdty" , "Diesel, 10ppm CIF NWE Sep12"],
["TYAU13 Cmdty" , "Diesel, 10ppm CIF NWE Sep13"],
["TYAU14 Cmdty" , "Diesel, 10ppm CIF NWE Sep14"],
["TYAU7 Cmdty" , "Diesel, 10ppm CIF NWE Sep17"],
["TYAU8 Cmdty" , "Diesel, 10ppm CIF NWE Sep18"],
["TYAV08 Cmdty" , "Diesel, 10ppm CIF NWE Oct08"],
["TYAV09 Cmdty" , "Diesel, 10ppm CIF NWE Oct09"],
["TYAV10 Cmdty" , "Diesel, 10ppm CIF NWE Oct10"],
["TYAV11 Cmdty" , "Diesel, 10ppm CIF NWE Oct11"],
["TYAV12 Cmdty" , "Diesel, 10ppm CIF NWE Oct12"],
["TYAV13 Cmdty" , "Diesel, 10ppm CIF NWE Oct13"],
["TYAV14 Cmdty" , "Diesel, 10ppm CIF NWE Oct14"],
["TYAV5 Cmdty" , "Diesel, 10ppm CIF NWE Oct15"],
["TYAV7 Cmdty" , "Diesel, 10ppm CIF NWE Oct17"],
["TYAV8 Cmdty" , "Diesel, 10ppm CIF NWE Oct18"],
["TYAX08 Cmdty" , "Diesel, 10ppm CIF NWE Nov08"],
["TYAX09 Cmdty" , "Diesel, 10ppm CIF NWE Nov09"],
["TYAX10 Cmdty" , "Diesel, 10ppm CIF NWE Nov10"],
["TYAX11 Cmdty" , "Diesel, 10ppm CIF NWE Nov11"],
["TYAX12 Cmdty" , "Diesel, 10ppm CIF NWE Nov12"],
["TYAX13 Cmdty" , "Diesel, 10ppm CIF NWE Nov13"],
["TYAX14 Cmdty" , "Diesel, 10ppm CIF NWE Nov14"],
["TYAX5 Cmdty" , "Diesel, 10ppm CIF NWE Nov15"],
["TYAX6 Cmdty" , "Diesel, 10ppm CIF NWE Nov16"],
["TYAX7 Cmdty" , "Diesel, 10ppm CIF NWE Nov17"],
["TYAX8 Cmdty" , "Diesel, 10ppm CIF NWE Nov18"],
["TYAZ08 Cmdty" , "Diesel, 10ppm CIF NWE Dec08"],
["TYAZ09 Cmdty" , "Diesel, 10ppm CIF NWE Dec09"],
["TYAZ10 Cmdty" , "Diesel, 10ppm CIF NWE Dec10"],
["TYAZ11 Cmdty" , "Diesel, 10ppm CIF NWE Dec11"],
["TYAZ12 Cmdty" , "Diesel, 10ppm CIF NWE Dec12"],
["TYAZ13 Cmdty" , "Diesel, 10ppm CIF NWE Dec13"],
["TYAZ14 Cmdty" , "Diesel, 10ppm CIF NWE Dec14"],
["TYAZ5 Cmdty" , "Diesel, 10ppm CIF NWE Dec15"],
["TYAZ7 Cmdty" , "Diesel, 10ppm CIF NWE Dec17"],
["TYAZ8 Cmdty" , "Diesel, 10ppm CIF NWE Dec18"],
["USWATYA Crncy" , "TYA Invoice SwapSprd 10Y"],
["TY 3M 50D VOL BVOL Cmdty" , "3 Month 50 Delta Implied Volatility for TY(TYA)"],
["600807 CH Equity" , "Shandong Tyan Home Co Ltd (China)"],
["TY APR16 25DP VOL BVOL Cmdty" , "April 2016 25 Delta Put Implied Volatility for TY(TYA)"],
["TYU6 Cmdty" , "US Treasury Note, 10Yr Sep16"],
["TY JUN16 25DP VOL BVOL Cmdty" , "June 2016 25 Delta Put Implied Volatility for TY(TYA)"],
["ISPIM SPA CDS EUR SR 5Y D14 Corp" , "Intesa Sanpaolo SpA"],
["TY 6M 100 VOL BVOL Cmdty" , "6 Month 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY APR16 10DP VOL BVOL Cmdty" , "April 2016 10 Delta Put Implied Volatility for TY(TYA)"],
["TY JUN16 15DC VOL BVOL Cmdty" , "June 2016 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 2M 25DP VOL BVOL Cmdty" , "2 Month 25 Delta Put Implied Volatility for TY(TYA)"],
["TY 1W 100 VOL BVOL Cmdty" , "1 Week 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY JUN16 25DC VOL BVOL Cmdty" , "June 2016 25 Delta Call Implied Volatility for TY(TYA)"],
["TY APR16 15DP VOL BVOL Cmdty" , "April 2016 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 1M ATM VOL BVOL Cmdty" , "1 Month At the Money Implied Volatility for TY(TYA)"],
["URAM RU Equity" , "Uralmashplant OJSC (Russia)"],
["TY MAY16 25DP VOL BVOL Cmdty" , "May 2016 25 Delta Put Implied Volatility for TY(TYA)"],
["TYZ5 Cmdty" , "US Treasury Note, 10Yr Dec15"],
["TYPM RU Equity" , "Tyazhpressmash OAO (Russia)"],
["TYM5 Cmdty" , "US Treasury Note, 10Yr Jun15"],
["TY 3M 25DP VOL BVOL Cmdty" , "3 Month 25 Delta Put Implied Volatility for TY(TYA)"],
["TY 2W 50D VOL BVOL Cmdty" , "2 Week 50 Delta Implied Volatility for TY(TYA)"],
["TY2 Cmdty" , "Generic 2nd US Treasury Note, 10Yr"],
["TY 6M 97.5 VOL BVOL Cmdty" , "6 Month 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY APR16 25DC VOL BVOL Cmdty" , "April 2016 25 Delta Call Implied Volatility for TY(TYA)"],
["TY JUN16 35DP VOL BVOL Cmdty" , "June 2016 35 Delta Put Implied Volatility for TY(TYA)"],
["TYU5 Cmdty" , "US Treasury Note, 10Yr Sep15"],
["URAMP* RU Equity" , "Uralmashplant OJSC (Russia)"],
["TYZ6 Cmdty" , "US Treasury Note, 10Yr Dec16"],
["TMAS RU Equity" , "TyazhMash OAO (Russia)"],
["TY APR16 35DP VOL BVOL Cmdty" , "April 2016 35 Delta Put Implied Volatility for TY(TYA)"],
["TY MAY16 25DC VOL BVOL Cmdty" , "May 2016 25 Delta Call Implied Volatility for TY(TYA)"],
["TY MAY16 35DP VOL BVOL Cmdty" , "May 2016 35 Delta Put Implied Volatility for TY(TYA)"],
["TY JUN16 15DP VOL BVOL Cmdty" , "June 2016 15 Delta Put Implied Volatility for TY(TYA)"],
["TY MAY16 15DP VOL BVOL Cmdty" , "May 2016 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 3W 50D VOL BVOL Cmdty" , "3 Week 50 Delta Implied Volatility for TY(TYA)"],
["ISPIM SPA CDS EUR SUB 5Y D14 Corp" , "Intesa Sanpaolo SpA"],
["TY 3M 110 VOL BVOL Cmdty" , "3 Month 110 % Moneyness Implied Volatility for TY(TYA)"],
["TY 1Y 100 VOL BVOL Cmdty" , "1 Year 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY 2M 25DC VOL BVOL Cmdty" , "2 Month 25 Delta Call Implied Volatility for TY(TYA)"],
["TY 3M 25DC VOL BVOL Cmdty" , "3 Month 25 Delta Call Implied Volatility for TY(TYA)"],
["TY 1W 50D VOL BVOL Cmdty" , "1 Week 50 Delta Implied Volatility for TY(TYA)"],
["TY JUN16 10DC VOL BVOL Cmdty" , "June 2016 10 Delta Call Implied Volatility for TY(TYA)"],
["TY MAR16 25DP VOL BVOL Cmdty" , "March 2016 25 Delta Put Implied Volatility for TY(TYA)"],
["TY MAY16 10DP VOL BVOL Cmdty" , "May 2016 10 Delta Put Implied Volatility for TY(TYA)"],
["TY MAY16 35DC VOL BVOL Cmdty" , "May 2016 35 Delta Call Implied Volatility for TY(TYA)"],
["2203 TT Equity" , "YEU Tyan Machinery MFG Co (Taiwan Stock Exchange)"],
["600807 CG Equity" , "Shandong Tyan Home Co Ltd (Shanghai)"],
[".T 6 09/01/2014 CRB Corp" , "PPCR: TYA NOTIONAL"],
[".T 6 03/04/2019 Corp" , "PPCR: NOTL BOND - TYA"],
["1262307D RU Equity" , "Tyazhmash ZAO"],
["3480 TT Equity" , "Tyan Computer Corp (Taiwan Stock Exchange)"],
["PPNO0451 Index" , "Tya Small Hydro Plant Norway"],
["TSGI RU Equity" , "Tyazhstankohydropress (Russia)"],
["TY 1W 5DP VOL BVOL Cmdty" , "1 Week 5 Delta Put Implied Volatility for TY(TYA)"],
["TY JUN16 35DC VOL BVOL Cmdty" , "June 2016 35 Delta Call Implied Volatility for TY(TYA)"],
["TY MAR16 50D VOL BVOL Cmdty" , "March 2016 50 Delta Implied Volatility for TY(TYA)"],
["TY 1Y ATM VOL BVOL Cmdty" , "1 Year At the Money Implied Volatility for TY(TYA)"],
["TY 3M 90 VOL BVOL Cmdty" , "3 Month 90 % Moneyness Implied Volatility for TY(TYA)"],
["TY 1Y 90 VOL BVOL Cmdty" , "1 Year 90 % Moneyness Implied Volatility for TY(TYA)"],
["TY 1Y 110 VOL BVOL Cmdty" , "1 Year 110 % Moneyness Implied Volatility for TY(TYA)"],
["TY 3Y 90 VOL BVOL Cmdty" , "3 Year 90 % Moneyness Implied Volatility for TY(TYA)"],
["TY 3Y 100 VOL BVOL Cmdty" , "3 Year 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY 3Y 110 VOL BVOL Cmdty" , "3 Year 110 % Moneyness Implied Volatility for TY(TYA)"],
["TY 5Y 90 VOL BVOL Cmdty" , "5 Year 90 % Moneyness Implied Volatility for TY(TYA)"],
["TY 5Y 100 VOL BVOL Cmdty" , "5 Year 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY 5Y 110 VOL BVOL Cmdty" , "5 Year 110 % Moneyness Implied Volatility for TY(TYA)"],
["TY 1M 97.5 VOL BVOL Cmdty" , "1 Month 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 1M 102.5 VOL BVOL Cmdty" , "1 Month 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 2M 97.5 VOL BVOL Cmdty" , "2 Month 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 2M 100 VOL BVOL Cmdty" , "2 Month 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY 2M 102.5 VOL BVOL Cmdty" , "2 Month 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 3M 97.5 VOL BVOL Cmdty" , "3 Month 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 6M 102.5 VOL BVOL Cmdty" , "6 Month 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 9M 97.5 VOL BVOL Cmdty" , "9 Month 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 9M 100 VOL BVOL Cmdty" , "9 Month 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY 9M 102.5 VOL BVOL Cmdty" , "9 Month 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 1Y 97.5 VOL BVOL Cmdty" , "1 Year 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 1Y 102.5 VOL BVOL Cmdty" , "1 Year 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 18M 97.5 VOL BVOL Cmdty" , "18 Month 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 18M 100 VOL BVOL Cmdty" , "18 Month 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY 18M 102.5 VOL BVOL Cmdty" , "18 Month 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 2Y 97.5 VOL BVOL Cmdty" , "2 Year 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 2Y 100 VOL BVOL Cmdty" , "2 Year 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY 2Y 102.5 VOL BVOL Cmdty" , "2 Year 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 3Y 97.5 VOL BVOL Cmdty" , "3 Year 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 3Y 102.5 VOL BVOL Cmdty" , "3 Year 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 4Y 97.5 VOL BVOL Cmdty" , "4 Year 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 4Y 100 VOL BVOL Cmdty" , "4 Year 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY 4Y 102.5 VOL BVOL Cmdty" , "4 Year 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 5Y 97.5 VOL BVOL Cmdty" , "5 Year 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 5Y 102.5 VOL BVOL Cmdty" , "5 Year 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 1M 90 VOL BVOL Cmdty" , "1 Month 90 % Moneyness Implied Volatility for TY(TYA)"],
["TY 1M 110 VOL BVOL Cmdty" , "1 Month 110 % Moneyness Implied Volatility for TY(TYA)"],
["TY 6M 90 VOL BVOL Cmdty" , "6 Month 90 % Moneyness Implied Volatility for TY(TYA)"],
["TY 6M 110 VOL BVOL Cmdty" , "6 Month 110 % Moneyness Implied Volatility for TY(TYA)"],
["TY 2M 10DC VOL BVOL Cmdty" , "2 Month 10 Delta Call Implied Volatility for TY(TYA)"],
["TY 2M 15DC VOL BVOL Cmdty" , "2 Month 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 2M 35DC VOL BVOL Cmdty" , "2 Month 35 Delta Call Implied Volatility for TY(TYA)"],
["TY 2M 5DC VOL BVOL Cmdty" , "2 Month 5 Delta Call Implied Volatility for TY(TYA)"],
["TY 6M 50D VOL BVOL Cmdty" , "6 Month 50 Delta Implied Volatility for TY(TYA)"],
["TY 1Y 50D VOL BVOL Cmdty" , "1 Year 50 Delta Implied Volatility for TY(TYA)"],
["TY 2M 5DP VOL BVOL Cmdty" , "2 Month 5 Delta Put Implied Volatility for TY(TYA)"],
["TY 1M 5DP VOL BVOL Cmdty" , "1 Month 5 Delta Put Implied Volatility for TY(TYA)"],
["TY 1M 15DP VOL BVOL Cmdty" , "1 Month 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 1M 10DC VOL BVOL Cmdty" , "1 Month 10 Delta Call Implied Volatility for TY(TYA)"],
["TY 9M 50D VOL BVOL Cmdty" , "9 Month 50 Delta Implied Volatility for TY(TYA)"],
["TY 9M 15DP VOL BVOL Cmdty" , "9 Month 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 3M 35DP VOL BVOL Cmdty" , "3 Month 35 Delta Put Implied Volatility for TY(TYA)"],
["TY 1M 35DP VOL BVOL Cmdty" , "1 Month 35 Delta Put Implied Volatility for TY(TYA)"],
["TY 1M 10DP VOL BVOL Cmdty" , "1 Month 10 Delta Put Implied Volatility for TY(TYA)"],
["TY 1W 97.5 VOL BVOL Cmdty" , "1 Week 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 1W 102.5 VOL BVOL Cmdty" , "1 Week 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 7Y 97.5 VOL BVOL Cmdty" , "7 Year 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 7Y 100 VOL BVOL Cmdty" , "7 Year 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY 7Y 102.5 VOL BVOL Cmdty" , "7 Year 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 10Y 97.5 VOL BVOL Cmdty" , "10 Year 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 10Y 100 VOL BVOL Cmdty" , "10 Year 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY 10Y 102.5 VOL BVOL Cmdty" , "10 Year 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 9M 35DP VOL BVOL Cmdty" , "9 Month 35 Delta Put Implied Volatility for TY(TYA)"],
["TY 1Y 35DP VOL BVOL Cmdty" , "1 Year 35 Delta Put Implied Volatility for TY(TYA)"],
["TY 5Y 5DC VOL BVOL Cmdty" , "5 Year 5 Delta Call Implied Volatility for TY(TYA)"],
["TY 3M 15DC VOL BVOL Cmdty" , "3 Month 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 2Y 10DC VOL BVOL Cmdty" , "2 Year 10 Delta Call Implied Volatility for TY(TYA)"],
["TY 6M 35DC VOL BVOL Cmdty" , "6 Month 35 Delta Call Implied Volatility for TY(TYA)"],
["TY 18M 35DC VOL BVOL Cmdty" , "18 Month 35 Delta Call Implied Volatility for TY(TYA)"],
["TY 7Y 25DC VOL BVOL Cmdty" , "7 Year 25 Delta Call Implied Volatility for TY(TYA)"],
["TY 4Y 35DC VOL BVOL Cmdty" , "4 Year 35 Delta Call Implied Volatility for TY(TYA)"],
["TY 3M 105 VOL BVOL Cmdty" , "3 Month 105 % Moneyness Implied Volatility for TY(TYA)"],
["TY 3M 95 VOL BVOL Cmdty" , "3 Month 95 % Moneyness Implied Volatility for TY(TYA)"],
["TY 2M 95 VOL BVOL Cmdty" , "2 Month 95 % Moneyness Implied Volatility for TY(TYA)"],
["TY 2M 105 VOL BVOL Cmdty" , "2 Month 105 % Moneyness Implied Volatility for TY(TYA)"],
["TY 5Y 35DC VOL BVOL Cmdty" , "5 Year 35 Delta Call Implied Volatility for TY(TYA)"],
["TY 5Y 25DP VOL BVOL Cmdty" , "5 Year 25 Delta Put Implied Volatility for TY(TYA)"],
["TY 1M 80 VOL BVOL Cmdty" , "1 Month 80 % Moneyness Implied Volatility for TY(TYA)"],
["TY 2M 80 VOL BVOL Cmdty" , "2 Month 80 % Moneyness Implied Volatility for TY(TYA)"],
["TY 6M 25DP VOL BVOL Cmdty" , "6 Month 25 Delta Put Implied Volatility for TY(TYA)"],
["TY 2W 97.5 VOL BVOL Cmdty" , "2 Week 97.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 2W 100 VOL BVOL Cmdty" , "2 Week 100 % Moneyness Implied Volatility for TY(TYA)"],
["TY 2W 102.5 VOL BVOL Cmdty" , "2 Week 102.5 % Moneyness Implied Volatility for TY(TYA)"],
["TY 3M 35DC VOL BVOL Cmdty" , "3 Month 35 Delta Call Implied Volatility for TY(TYA)"],
["TY 1W 10DP VOL BVOL Cmdty" , "1 Week 10 Delta Put Implied Volatility for TY(TYA)"],
["TY 1W 15DP VOL BVOL Cmdty" , "1 Week 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 1W 25DP VOL BVOL Cmdty" , "1 Week 25 Delta Put Implied Volatility for TY(TYA)"],
["TY 1W 35DP VOL BVOL Cmdty" , "1 Week 35 Delta Put Implied Volatility for TY(TYA)"],
["TY 1W 35DC VOL BVOL Cmdty" , "1 Week 35 Delta Call Implied Volatility for TY(TYA)"],
["TY 1W 25DC VOL BVOL Cmdty" , "1 Week 25 Delta Call Implied Volatility for TY(TYA)"],
["TY 1W 15DC VOL BVOL Cmdty" , "1 Week 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 1W 10DC VOL BVOL Cmdty" , "1 Week 10 Delta Call Implied Volatility for TY(TYA)"],
["TY 1W 5DC VOL BVOL Cmdty" , "1 Week 5 Delta Call Implied Volatility for TY(TYA)"],
["TY 1M 35DC VOL BVOL Cmdty" , "1 Month 35 Delta Call Implied Volatility for TY(TYA)"],
["TY 1M 15DC VOL BVOL Cmdty" , "1 Month 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 1M 5DC VOL BVOL Cmdty" , "1 Month 5 Delta Call Implied Volatility for TY(TYA)"],
["TY 2M 10DP VOL BVOL Cmdty" , "2 Month 10 Delta Put Implied Volatility for TY(TYA)"],
["TY 2M 15DP VOL BVOL Cmdty" , "2 Month 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 2M 35DP VOL BVOL Cmdty" , "2 Month 35 Delta Put Implied Volatility for TY(TYA)"],
["TY 3M 5DP VOL BVOL Cmdty" , "3 Month 5 Delta Put Implied Volatility for TY(TYA)"],
["TY 3M 10DP VOL BVOL Cmdty" , "3 Month 10 Delta Put Implied Volatility for TY(TYA)"],
["TY 3M 15DP VOL BVOL Cmdty" , "3 Month 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 3M 10DC VOL BVOL Cmdty" , "3 Month 10 Delta Call Implied Volatility for TY(TYA)"],
["TY 3M 5DC VOL BVOL Cmdty" , "3 Month 5 Delta Call Implied Volatility for TY(TYA)"],
["TY 6M 5DP VOL BVOL Cmdty" , "6 Month 5 Delta Put Implied Volatility for TY(TYA)"],
["TY 6M 10DP VOL BVOL Cmdty" , "6 Month 10 Delta Put Implied Volatility for TY(TYA)"],
["TY 6M 15DP VOL BVOL Cmdty" , "6 Month 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 6M 35DP VOL BVOL Cmdty" , "6 Month 35 Delta Put Implied Volatility for TY(TYA)"],
["TY 6M 25DC VOL BVOL Cmdty" , "6 Month 25 Delta Call Implied Volatility for TY(TYA)"],
["TY 6M 15DC VOL BVOL Cmdty" , "6 Month 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 6M 10DC VOL BVOL Cmdty" , "6 Month 10 Delta Call Implied Volatility for TY(TYA)"],
["TY 6M 5DC VOL BVOL Cmdty" , "6 Month 5 Delta Call Implied Volatility for TY(TYA)"],
["TY 9M 5DP VOL BVOL Cmdty" , "9 Month 5 Delta Put Implied Volatility for TY(TYA)"],
["TY 9M 10DP VOL BVOL Cmdty" , "9 Month 10 Delta Put Implied Volatility for TY(TYA)"],
["TY 9M 25DP VOL BVOL Cmdty" , "9 Month 25 Delta Put Implied Volatility for TY(TYA)"],
["TY 9M 35DC VOL BVOL Cmdty" , "9 Month 35 Delta Call Implied Volatility for TY(TYA)"],
["TY 9M 25DC VOL BVOL Cmdty" , "9 Month 25 Delta Call Implied Volatility for TY(TYA)"],
["TY 9M 15DC VOL BVOL Cmdty" , "9 Month 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 9M 10DC VOL BVOL Cmdty" , "9 Month 10 Delta Call Implied Volatility for TY(TYA)"],
["TY 9M 5DC VOL BVOL Cmdty" , "9 Month 5 Delta Call Implied Volatility for TY(TYA)"],
["TY 1Y 5DP VOL BVOL Cmdty" , "1 Year 5 Delta Put Implied Volatility for TY(TYA)"],
["TY 1Y 10DP VOL BVOL Cmdty" , "1 Year 10 Delta Put Implied Volatility for TY(TYA)"],
["TY 1Y 15DP VOL BVOL Cmdty" , "1 Year 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 1Y 25DP VOL BVOL Cmdty" , "1 Year 25 Delta Put Implied Volatility for TY(TYA)"],
["TY 1Y 35DC VOL BVOL Cmdty" , "1 Year 35 Delta Call Implied Volatility for TY(TYA)"],
["TY 1Y 25DC VOL BVOL Cmdty" , "1 Year 25 Delta Call Implied Volatility for TY(TYA)"],
["TY 1Y 15DC VOL BVOL Cmdty" , "1 Year 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 1Y 10DC VOL BVOL Cmdty" , "1 Year 10 Delta Call Implied Volatility for TY(TYA)"],
["TY 1Y 5DC VOL BVOL Cmdty" , "1 Year 5 Delta Call Implied Volatility for TY(TYA)"],
["TY 18M 5DP VOL BVOL Cmdty" , "18 Month 5 Delta Put Implied Volatility for TY(TYA)"],
["TY 18M 10DP VOL BVOL Cmdty" , "18 Month 10 Delta Put Implied Volatility for TY(TYA)"],
["TY 18M 15DP VOL BVOL Cmdty" , "18 Month 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 18M 25DP VOL BVOL Cmdty" , "18 Month 25 Delta Put Implied Volatility for TY(TYA)"],
["TY 18M 35DP VOL BVOL Cmdty" , "18 Month 35 Delta Put Implied Volatility for TY(TYA)"],
["TY 18M 50D VOL BVOL Cmdty" , "18 Month 50 Delta Implied Volatility for TY(TYA)"],
["TY 18M 25DC VOL BVOL Cmdty" , "18 Month 25 Delta Call Implied Volatility for TY(TYA)"],
["TY 18M 15DC VOL BVOL Cmdty" , "18 Month 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 18M 10DC VOL BVOL Cmdty" , "18 Month 10 Delta Call Implied Volatility for TY(TYA)"],
["TY 18M 5DC VOL BVOL Cmdty" , "18 Month 5 Delta Call Implied Volatility for TY(TYA)"],
["TY 2Y 5DP VOL BVOL Cmdty" , "2 Year 5 Delta Put Implied Volatility for TY(TYA)"],
["TY 2Y 10DP VOL BVOL Cmdty" , "2 Year 10 Delta Put Implied Volatility for TY(TYA)"],
["TY 2Y 15DP VOL BVOL Cmdty" , "2 Year 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 2Y 25DP VOL BVOL Cmdty" , "2 Year 25 Delta Put Implied Volatility for TY(TYA)"],
["TY 2Y 35DP VOL BVOL Cmdty" , "2 Year 35 Delta Put Implied Volatility for TY(TYA)"],
["TY 2Y 50D VOL BVOL Cmdty" , "2 Year 50 Delta Implied Volatility for TY(TYA)"],
["TY 2Y 35DC VOL BVOL Cmdty" , "2 Year 35 Delta Call Implied Volatility for TY(TYA)"],
["TY 2Y 25DC VOL BVOL Cmdty" , "2 Year 25 Delta Call Implied Volatility for TY(TYA)"],
["TY 2Y 15DC VOL BVOL Cmdty" , "2 Year 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 2Y 5DC VOL BVOL Cmdty" , "2 Year 5 Delta Call Implied Volatility for TY(TYA)"],
["TY 3Y 5DP VOL BVOL Cmdty" , "3 Year 5 Delta Put Implied Volatility for TY(TYA)"],
["TY 3Y 10DP VOL BVOL Cmdty" , "3 Year 10 Delta Put Implied Volatility for TY(TYA)"],
["TY 3Y 15DP VOL BVOL Cmdty" , "3 Year 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 3Y 25DP VOL BVOL Cmdty" , "3 Year 25 Delta Put Implied Volatility for TY(TYA)"],
["TY 3Y 35DP VOL BVOL Cmdty" , "3 Year 35 Delta Put Implied Volatility for TY(TYA)"],
["TY 3Y 50D VOL BVOL Cmdty" , "3 Year 50 Delta Implied Volatility for TY(TYA)"],
["TY 3Y 35DC VOL BVOL Cmdty" , "3 Year 35 Delta Call Implied Volatility for TY(TYA)"],
["TY 3Y 25DC VOL BVOL Cmdty" , "3 Year 25 Delta Call Implied Volatility for TY(TYA)"],
["TY 3Y 15DC VOL BVOL Cmdty" , "3 Year 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 3Y 10DC VOL BVOL Cmdty" , "3 Year 10 Delta Call Implied Volatility for TY(TYA)"],
["TY 3Y 5DC VOL BVOL Cmdty" , "3 Year 5 Delta Call Implied Volatility for TY(TYA)"],
["TY 4Y 5DP VOL BVOL Cmdty" , "4 Year 5 Delta Put Implied Volatility for TY(TYA)"],
["TY 4Y 10DP VOL BVOL Cmdty" , "4 Year 10 Delta Put Implied Volatility for TY(TYA)"],
["TY 4Y 15DP VOL BVOL Cmdty" , "4 Year 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 4Y 25DP VOL BVOL Cmdty" , "4 Year 25 Delta Put Implied Volatility for TY(TYA)"],
["TY 4Y 35DP VOL BVOL Cmdty" , "4 Year 35 Delta Put Implied Volatility for TY(TYA)"],
["TY 4Y 50D VOL BVOL Cmdty" , "4 Year 50 Delta Implied Volatility for TY(TYA)"],
["TY 4Y 25DC VOL BVOL Cmdty" , "4 Year 25 Delta Call Implied Volatility for TY(TYA)"],
["TY 4Y 15DC VOL BVOL Cmdty" , "4 Year 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 4Y 10DC VOL BVOL Cmdty" , "4 Year 10 Delta Call Implied Volatility for TY(TYA)"],
["TY 4Y 5DC VOL BVOL Cmdty" , "4 Year 5 Delta Call Implied Volatility for TY(TYA)"],
["TY 5Y 5DP VOL BVOL Cmdty" , "5 Year 5 Delta Put Implied Volatility for TY(TYA)"],
["TY 5Y 10DP VOL BVOL Cmdty" , "5 Year 10 Delta Put Implied Volatility for TY(TYA)"],
["TY 5Y 15DP VOL BVOL Cmdty" , "5 Year 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 5Y 35DP VOL BVOL Cmdty" , "5 Year 35 Delta Put Implied Volatility for TY(TYA)"],
["TY 5Y 50D VOL BVOL Cmdty" , "5 Year 50 Delta Implied Volatility for TY(TYA)"],
["TY 5Y 25DC VOL BVOL Cmdty" , "5 Year 25 Delta Call Implied Volatility for TY(TYA)"],
["TY 5Y 15DC VOL BVOL Cmdty" , "5 Year 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 5Y 10DC VOL BVOL Cmdty" , "5 Year 10 Delta Call Implied Volatility for TY(TYA)"],
["TY 7Y 5DP VOL BVOL Cmdty" , "7 Year 5 Delta Put Implied Volatility for TY(TYA)"],
["TY 7Y 10DP VOL BVOL Cmdty" , "7 Year 10 Delta Put Implied Volatility for TY(TYA)"],
["TY 7Y 15DP VOL BVOL Cmdty" , "7 Year 15 Delta Put Implied Volatility for TY(TYA)"],
["TY 7Y 25DP VOL BVOL Cmdty" , "7 Year 25 Delta Put Implied Volatility for TY(TYA)"],
["TY 7Y 35DP VOL BVOL Cmdty" , "7 Year 35 Delta Put Implied Volatility for TY(TYA)"],
["TY 7Y 50D VOL BVOL Cmdty" , "7 Year 50 Delta Implied Volatility for TY(TYA)"],
["TY 7Y 35DC VOL BVOL Cmdty" , "7 Year 35 Delta Call Implied Volatility for TY(TYA)"],
["TY 7Y 15DC VOL BVOL Cmdty" , "7 Year 15 Delta Call Implied Volatility for TY(TYA)"],
["TY 7Y 10DC VOL BVOL Cmdty" , "7 Year 10 Delta Call Implied Volatility for TY(TYA)"],
["TY 7Y 5DC VOL BVOL Cmdty" , "7 Year 5 Delta Call Implied Volatility for TY(TYA)"],
["TY 10Y 5DP VOL BVOL Cmdty" , "10 Year 5 Delta Put Implied Volatility for TY(TYA)"],
["TY 10Y 10DP VOL BVOL Cmdty" , "10 Year 10 Delta Put Implied Volatility for TY(TYA)"],
["TSLA US Equity" , "Tesla Motors Inc (U.S.)"],
["TESLA BZ Equity" , "Santander FIC FI PB Tesla Multimercado Credito Privado (Brazil)"],
["TSLA Corp" , "Tesla Motors Inc (Multiple Matches)"],
["TSLA UW Equity" , "Tesla Motors Inc (NASDAQ GS)"],
["TSLA UQ Equity" , "Tesla Motors Inc (NASDAQ GM)"],
["TL0 GY Equity" , "Tesla Motors Inc (Xetra)"],
["AERO SG Equity" , "Aerodrom Nikola Tesla AD Beograd (Belgrade)"],
["ERNTRA CZ Equity" , "Ericsson Nikola Tesla dd (Croatia)"],
["TL0 GR Equity" , "Tesla Motors Inc (Germany)"],
["TL0 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["ERNTRA ZA Equity" , "Ericsson Nikola Tesla dd (Zagreb)"],
["TL0 TH Equity" , "Tesla Motors Inc (Tradegate)"],
["TSLA SW Equity" , "Tesla Motors Inc (Switzerland)"],
["BL174800 Corp" , "Tesla Motors Loan USD REV 06/10/2020"],
["TESLA CP Equity" , "Tesla AS (Prague)"],
["TXL CN Equity" , "Tesla Exploration Ltd (Canada)"],
["TSLA UP Equity" , "Tesla Motors Inc (NYSE Arca)"],
["TSLA* MM Equity" , "Tesla Motors Inc (Mexico)"],
["ERCSTESL Index" , "US Auto Sales Tesla Total Light Vehicle"],
["WTSAGV SW Equity" , "Tesla Motors Inc (Switzerland)"],
["TSLG RU Equity" , "Tesla Group OAO (Russia)"],
["TSLPC SW Equity" , "Tesla Motors Inc (Switzerland)"],
["TXLZF US Equity" , "Tesla Exploration Ltd (U.S.)"],
["EIDT US Equity" , "Tesla Vision Corp (U.S.)"],
["TESLALKY Index" , "Tesoro Salt Lake City UT Refinery 4900-bpd Alkylation Unit Plant Total (PADD 4)"],
["TESLALTE Index" , "Tesoro Corp Salt Lake City Refinery Utah USA (PADD 4) Alkylates Unit"],
["VTTSLT SW Equity" , "Tesla Motors Inc (Switzerland)"],
["1026612D AU Equity" , "Tesla Motors Australia Pty Ltd"],
["TESKR CP Equity" , "Tesla Karlin AS (Prague)"],
["VS8LX2 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["TSLAD=M6 OC Equity" , "Tesla Motors Inc Jun 2016 Dividend Neutral Future (OneChicago)"],
["TL0 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["TSLAD=H6 OC Equity" , "Tesla Motors Inc Mar 2016 Dividend Neutral Future (OneChicago)"],
["TSLA UC Equity" , "Tesla Motors Inc (National Stock Exchange)"],
["UT79K2 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["TSL4=M6 GR Equity" , "Tesla Motors Inc Jun 2016 Future (Eurex Deutschland)"],
["TSLJA SW Equity" , "Tesla Motors Inc (Switzerland)"],
["VTTSLK SW Equity" , "Tesla Motors Inc (Switzerland)"],
["TSL4=H6 GR Equity" , "Tesla Motors Inc Mar 2016 Future (Eurex Deutschland)"],
["8931310Z LN Equity" , "Tesla Exploration International Ltd"],
["TSLA UD Equity" , "Tesla Motors Inc (FINRA ADF)"],
["UT79K3 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["WTSAZV SW Equity" , "Tesla Motors Inc (Switzerland)"],
["CW97P3 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["UT79JQ GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["TSLA SG Equity" , "Tesla Fabrika Sijalica AD (Belgrade)"],
["TSLA VY Equity" , "Tesla Motors Inc (BATS Y)"],
["UT79K2 GR Equity" , "Tesla Motors Inc (Germany)"],
["UT79K2 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["1087Z FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["HU1QXZ GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["TD53LV GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["TESJH CP Equity" , "Tesla Jihlava AS (Prague)"],
["TSLACHF XA Equity" , "Tesla Motors Inc (CEESEG OTC and LJSE Block Trades)"],
["TSLACHF XW Equity" , "Tesla Motors Inc (SIX Off-Order-Book)"],
["UZ5ZBV GR Equity" , "Tesla Motors Inc (Germany)"],
["VTTSLN SW Equity" , "Tesla Motors Inc (Switzerland)"],
["0232101Z SH Equity" , "Tesla Motors Inc"],
["0651778D LN Equity" , "Tesla Motors Ltd"],
["MKOS US Equity" , "Tesla Vision Corp (U.S.)"],
["TD53LV GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["TSLV US Equity" , "Tesla Vision Corp (U.S.)"],
["UI849J IM Equity" , "Tesla Motors Inc (Borsa Italiana)"],
["TSL4=4 GR Equity" , "Tesla Motors Inc 4th Generic Future (Eurex Deutschland)"],
["TSL4=J6 GR Equity" , "Tesla Motors Inc Apr 2016 Future (Eurex Deutschland)"],
["TSLAD=U6 OC Equity" , "Tesla Motors Inc Sep 2016 Dividend Neutral Future (OneChicago)"],
["TSLG=H6 SA Equity" , "Tesla Motors Inc Mar 2016 Future (South African Futures Exchange)"],
["7010C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["8786C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["BF174799 Corp" , "Tesla Motors Loan USD DEAL 06/10/2020"],
["FRVHTES Index" , "France New Car Registrations Tesla"],
["NRX CN Equity" , "Tesla Exploration Ltd (Canada)"],
["SPVHTESL Index" , "Spain New Car Registrations TESLA"],
["TSL9RA BK Equity" , "Tesla dd Brcko (Banja Luka)"],
["TSLA SE Equity" , "Tesla Motors Inc (SIX)"],
["TSLAJB SW Equity" , "Tesla Motors Inc (Switzerland)"],
["UT79K2 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["VS8LX2 GR Equity" , "Tesla Motors Inc (Germany)"],
["TSL4=V5 GR Equity" , "Tesla Motors Inc Oct 2015 Future (Eurex Deutschland)"],
["0679274D IM Equity" , "Tesla Energy Srl"],
["PLT5T231 Index" , "Midway Power LLC TESLA Power Project Gas Plant /CA"],
["0764522D PW Equity" , "Tesla Recycling SA"],
["CC5W8W GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W8W GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W8W GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CW92QL GR Equity" , "Tesla Motors Inc (Germany)"],
["TSLA VJ Equity" , "Tesla Motors Inc (EDGA)"],
["TSLA VK Equity" , "Tesla Motors Inc (EDGX)"],
["TSLAJB SX Equity" , "Tesla Motors Inc (SIX Structured Products)"],
["TSLEL CP Equity" , "Tesla Elmi AS (Prague)"],
["UT02R5 GR Equity" , "Tesla Motors Inc (Germany)"],
["VS7QYC GR Equity" , "Tesla Motors Inc (Germany)"],
["VS7YHC GR Equity" , "Tesla Motors Inc (Germany)"],
["VS8LYA GR Equity" , "Tesla Motors Inc (Germany)"],
["VS8LYC GR Equity" , "Tesla Motors Inc (Germany)"],
["XM9Z15 GR Equity" , "Tesla Motors Inc (Germany)"],
["TSL4=6 GR Equity" , "Tesla Motors Inc 6th Generic Future (Eurex Deutschland)"],
["TSL4=Z6 GR Equity" , "Tesla Motors Inc Dec 2016 Future (Eurex Deutschland)"],
["TSLD=2 SA Equity" , "Tesla Motors Inc 2nd Generic Dividend Future (South African Futures Exchange)"],
["TSL4=A GR Equity" , "Tesla Motors Inc Future (Eurex Deutschland)"],
["3683838Z SP Equity" , "Tesla Holdings Pty Ltd"],
["CD4YJE GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CD4YJE GR Equity" , "Tesla Motors Inc (Germany)"],
["5536469Z SG Equity" , "JP Aerodrom Nikola Tesla Beograd"],
["CD4YJE GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W8W GR Equity" , "Tesla Motors Inc (Germany)"],
["CD4YJE GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CD4YJF GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CD4YJF GR Equity" , "Tesla Motors Inc (Germany)"],
["CD4YJF GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CD4YJF GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CD4YJG GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CD4YJG GR Equity" , "Tesla Motors Inc (Germany)"],
["CD4YJG GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CD4YJG GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CD4YJH GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CD4YJH GR Equity" , "Tesla Motors Inc (Germany)"],
["CD4YJH GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CD4YJH GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CD4YJJ GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CD4YJJ GR Equity" , "Tesla Motors Inc (Germany)"],
["CD4YJJ GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CD4YJJ GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["D160Z FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["FDRYTESF Index" , "Tesla Sezam - Foundry"],
["FDRYTEST Index" , "Tesla Sezam - Total"],
["FDRYTSFI Index" , "Tesla Sezam - Fnd/IDM"],
["GNTKG072 Index" , "Midway Power LLC TESLA Power Project GenCode GTG1"],
["GNTKG073 Index" , "Midway Power LLC TESLA Power Project GenCode GTG2"],
["GNTKG074 Index" , "Midway Power LLC TESLA Power Project GenCode GTG3"],
["GNTKG075 Index" , "Midway Power LLC TESLA Power Project GenCode GTG4"],
["GNTKG076 Index" , "Midway Power LLC TESLA Power Project GenCode STG1"],
["GNTKG077 Index" , "Midway Power LLC TESLA Power Project GenCode STG2"],
["H303147-34 Client" , "SANTANDER FIC FI PB TESLA MULT CP"],
["H64066-21 Client" , "TESLA FI PREVIDENCIARIO MULTIMERCADO"],
["MP07004 Index" , "Tesla Motors Reno Battery Manufacturing Plant"],
["PGN8A116 Index" , "Tesla EIA ID: 7233 HY-1/CO"],
["PLT8A116 Index" , "Tesla Hydro Power Facility/CO"],
["PWRS0016 Index" , "Nikola Tesla A Coal Plant Serbia"],
["PWRS0017 Index" , "Nikola Tesla B Lignite Plant Serbia"],
["TL0 GM Equity" , "Tesla Motors Inc (Munich)"],
["TSLG RR Equity" , "Tesla Group OAO (MOEX)"],
["TXL QF Equity" , "Tesla Exploration Ltd (Aequitas NEO Lit Book)"],
["TXL TK Equity" , "Tesla Exploration Ltd (LiquidNet)"],
["TXL TX Equity" , "Tesla Exploration Ltd (Chi-X Toronto)"],
["TSL4=1 GR Equity" , "Tesla Motors Inc 1st Generic Future (Eurex Deutschland)"],
["TSL4=7 GR Equity" , "Tesla Motors Inc 7th Generic Future (Eurex Deutschland)"],
["TSL4=V6 GR Equity" , "Tesla Motors Inc Oct 2016 Future (Eurex Deutschland)"],
["TSLG=M6 SA Equity" , "Tesla Motors Inc Jun 2016 Future (South African Futures Exchange)"],
["TSLA=A OC Equity" , "Tesla Motors Inc Future (OneChicago)"],
["TSLAD=A OC Equity" , "Tesla Motors Inc Dividend Neutral Future (OneChicago)"],
["TSLD=A SA Equity" , "Tesla Motors Inc Dividend Future (South African Futures Exchange)"],
["TSLG=A SA Equity" , "Tesla Motors Inc Future (South African Futures Exchange)"],
["0038C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["0040578D US Equity" , "Tesla Electric Armature & Machine Inc"],
["0040579D US Equity" , "Tesla Industries Inc"],
["0076875D US Equity" , "Tesla Systems Inc"],
["0089368D US Equity" , "Tesla Laboratories Inc"],
["0165486Z US Equity" , "Tesla Offshore LLC"],
["0301911D SG Equity" , "Tesla AD"],
["0331642D CP Equity" , "Tesla Votice AS"],
["0443450D US Equity" , "Everson Tesla Inc"],
["0491375D RU Equity" , "SK Tesla OOO"],
["0569C2 MK Equity" , "Tesla Motors Inc (Bursa Malaysia)"],
["0713376D US Equity" , "Tesla Miami LC"],
["0832181D US Equity" , "Tesla Government Inc"],
["0912646D PW Equity" , "Tesla Metal SP ZOO Spolka Komandytowo Akcyjna"],
["0916612D CP Equity" , "Tesla Akciova Spolecnost"],
["0962168D US Equity" , "Tesla Expls Ltd (U.S.)"],
["0977922D CP Equity" , "Tesla Jihlava Sro"],
["0A1E90 AV Equity" , "Tesla Motors Inc (Vienna)"],
["0A1E91 AV Equity" , "Tesla Motors Inc (Vienna)"],
["0A1E92 AV Equity" , "Tesla Motors Inc (Vienna)"],
["0A1FTV AV Equity" , "Tesla Motors Inc (Vienna)"],
["0A1HT4 AV Equity" , "Tesla Motors Inc (Vienna)"],
["0A1HT5 AV Equity" , "Tesla Motors Inc (Vienna)"],
["1006336D PW Equity" , "Tesla Sp zoo"],
["1078533D BB Equity" , "Tesla Motors Belgium SPRL"],
["1086Z FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["1088Z FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["1110561D CP Equity" , "Tesla Military Technologies AS"],
["1229679D NO Equity" , "Tesla Motors Norway AS"],
["1238273D US Equity" , "Tesla Enterprises LLC"],
["1244119D SW Equity" , "Tesla Motors Switzerland GmbH"],
["128509Z US Equity" , "Tesla Vineyard LP"],
["1330996D CZ Equity" , "Tesla Kabeli DOO"],
["1644224Z LN Equity" , "Tesla Engineering Ltd"],
["1650C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["1698Z FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["1702360Z LN Equity" , "Tesla Ltd"],
["1TEP01A PZ Equity" , "Tesla Piestany AS (ISDX)"],
["1TLH01A PZ Equity" , "Tesla Liptovsky Hradok AS (ISDX)"],
["1TLH0T B3 Equity" , "Tesla Liptovsky Hradok AS (Blockmatch)"],
["1TLH0T L3 Equity" , "Tesla Liptovsky Hradok AS (Liquidnet)"],
["1TLH0T S2 Equity" , "Tesla Liptovsky Hradok AS (UBS MTF)"],
["2529Z AU Equity" , "Tesla 10 Pty Ltd"],
["2633651Z US Equity" , "Tesla Management Inc"],
["2633659Z US Equity" , "Tesla Inc"],
["3144341Q EO Equity" , "Tesla Piestany AS (OTC Composite)"],
["3144345Q EU Equity" , "Tesla Piestany AS (European Composite)"],
["3144349Q EU Equity" , "Tesla Piestany AS (European Composite)"],
["3144353Q EO Equity" , "Tesla Piestany AS (OTC Composite)"],
["3155431Q EO Equity" , "Tesla Liptovsky Hradok AS (OTC Composite)"],
["3155435Q EU Equity" , "Tesla Liptovsky Hradok AS (European Composite)"],
["3511374Z CN Equity" , "Tesla Exploration Ltd/Old"],
["3557T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3564T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3565T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3566T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3567T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3570T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3571T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3573T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3574T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3576T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3577T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3584T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3585T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3586T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3587T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3589T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3590T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3597T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3598T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3599T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3601T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["3602T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["4156Z FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["4157Z FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["4665Z FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["4666Z FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["4849Z FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["4915607Z US Equity" , "Tesla Power & Automation Inc"],
["545120Z IM Equity" , "Tesla Srl"],
["5979C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["5H46Z FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6239959Z CP Equity" , "Tesla Blatna AS"],
["6596156Z IN Equity" , "Tesla Transformers Ltd"],
["6598T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6599T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6600T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6601T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6602T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6603T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6604T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6605T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6606T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6607T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6608T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6609T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6610T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6611T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["6612T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7005469Z CP Equity" , "Tesla Holding AS"],
["7012C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7015C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7017C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7021C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7022C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7027C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7033C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7058C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7066C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7089C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7567748Z SG Equity" , "Termoelektrane Nikola Tesla doo/Obrenovac"],
["7960T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7961T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7962T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7963T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7964T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7965T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7968T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7969T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7970T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7971T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["7972T FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["8800C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["8816C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["8845S FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["8846S FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["8847S FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["8848S FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["8849S FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["9059C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["9060C FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["9220313Z RU Equity" , "Tesla OOO"],
["A372S FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["A373S FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["A374S FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["A375S FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["A376S FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["A377S FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["A378S FP Equity" , "Tesla Motors Inc (Euronext Paris)"],
["CC5W8T GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W8T GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W8T GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W8T GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W8U GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W8U GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W8U GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W8U GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W8V GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W8V GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W8V GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W8V GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W8X GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W8X GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W8X GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W8X GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W8Y GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W8Y GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W8Y GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W8Y GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W8Z GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W8Z GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W8Z GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W8Z GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W90 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W90 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W90 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W90 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W91 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W91 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W91 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W91 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W92 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W92 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W92 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W92 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W93 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W93 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W93 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W93 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W94 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W94 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W94 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W94 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W95 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W95 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W95 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W95 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W96 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W96 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W96 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W96 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W97 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W97 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W97 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W97 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W98 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W98 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W98 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W98 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W99 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W99 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W99 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W99 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9A GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9A GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9A GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9A GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9B GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9B GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9B GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9B GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9C GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9C GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9C GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9C GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9D GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9D GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9D GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9D GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9E GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9E GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9E GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9E GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9F GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9F GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9F GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9F GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9G GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9G GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9G GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9G GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9H GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9H GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9H GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9H GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9J GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9J GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9J GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9J GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9K GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9K GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9K GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9K GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9L GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9L GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9L GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9L GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9M GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9M GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9M GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9M GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9N GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9N GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9N GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9N GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9P GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9P GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9P GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9P GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9Q GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9Q GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9Q GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9Q GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9R GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9R GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9R GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9R GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9S GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9S GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9S GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9S GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9T GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9T GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9T GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9T GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9U GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9U GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9U GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9U GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9V GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9V GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9V GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9V GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9W GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9W GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9W GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9W GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC5W9X GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC5W9X GR Equity" , "Tesla Motors Inc (Germany)"],
["CC5W9X GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC5W9X GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC6BTV GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC6BTV GR Equity" , "Tesla Motors Inc (Germany)"],
["CC6BTV GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC6BTV GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC6BTW GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC6BTW GR Equity" , "Tesla Motors Inc (Germany)"],
["CC6BTW GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC6BTW GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC6BTX GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC6BTX GR Equity" , "Tesla Motors Inc (Germany)"],
["CC6BTX GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC6BTX GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC7H91 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC7H91 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC7H91 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC7H91 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC7J0P GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC7J0P GR Equity" , "Tesla Motors Inc (Germany)"],
["CC7J0P GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC7J0P GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC7J0Q GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC7J0Q GR Equity" , "Tesla Motors Inc (Germany)"],
["CC7J0Q GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC7J0Q GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC7RFZ GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC7RFZ GR Equity" , "Tesla Motors Inc (Germany)"],
["CC7RFZ GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC7RFZ GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC7RG0 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC7RG0 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC7RG0 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC7RG0 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC7RG1 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC7RG1 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC7RG1 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC7RG1 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC7RG2 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC7RG2 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC7RG2 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC7RG2 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC7RG3 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC7RG3 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC7RG3 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC7RG3 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC7RG4 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC7RG4 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC7RG4 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC7RG4 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC7RG5 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC7RG5 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC7RG5 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
["CC7RG5 GW Equity" , "Tesla Motors Inc (Stuttgart Warrants)"],
["CC7RG6 GF Equity" , "Tesla Motors Inc (Frankfurt)"],
["CC7RG6 GR Equity" , "Tesla Motors Inc (Germany)"],
["CC7RG6 GS Equity" , "Tesla Motors Inc (Stuttgart)"],
          ["1128 HK Equity","Wynn Macau Ltd (Hong Kong)"],
		  ["1122 HK Equity","Qingling Motors Co Ltd (Hong Kong)"],
		  ["1125 HK Equity","Lai Fung Holdings Ltd (Hong Kong)"],
		  ["1124z MK Equity","Feration of Malaysia (Bursa Malaysia)"], 
         ];

         